### ISSUE TITLE
not able to update APKs 

### ISSUE THREAD

**Issue by dingsbums** [Map-A-Droid/MAD#1181]
it's either that or a simple [W] Unable to import the APK. [Errno 32] Broken pipe

```
[07-28 05:19:07.95] [           system] [W] Unable to import the APK.
[2021-07-28 05:19:10,323] ERROR in app: Exception on /apk_update_status [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 788, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/mad_env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/mad_env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/mad_env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/mad_env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/mad_env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/mad_env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/MAD/mapadroid/madmin/routes/apks.py", line 46, in apk_update_status
    apk_info: MADapks = get_apk_status(self.storage_obj)
  File "/home/user/MAD/mapadroid/mad_apk/utils.py", line 121, in get_apk_status
    (package_info, status_code) = lookup_package_info(storage_obj, package, arch)
  File "/home/user/MAD/mapadroid/mad_apk/utils.py", line 245, in lookup_package_info
    package_info = storage_obj.get_current_package_info(package)
  File "<string>", line 2, in get_current_package_info
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 792, in _callmethod
    self._connect()
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 779, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

```

**Comment by Expl0dingBanana** [comment]
Does this problem persist after restarting MAD?
