### ISSUE TITLE
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason

### ISSUE THREAD

**Issue by kduytsch** [Map-A-Droid/MAD#126]
During some analysis, we discovered that from time to time a connection problem is ruining the whole webSocket. It looks like a device disconnect, which causes an unhandled error which beaks the socket. 
After that all devices are failing and can't be recovered

The exception is : 
`2019-03-12 15:31:59,154 [           scanner][WebsocketServer][   ERROR] retrieve_next_send: connection closed, returning None
2019-03-12 15:31:59,156 [           scanner][      protocol][ WARNING] Unexpected exception in keepalive ping task
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.6/dist-packages/websockets/framing.py", line 99, in read
    data = yield from reader(2)
  File "/usr/lib/python3.6/asyncio/streams.py", line 672, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 984, in keepalive_ping
    ping_waiter = yield from self.ping()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 583, in ping
    yield from self.ensure_open()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 646, in ensure_open
    ) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
2019-03-12 15:31:59,159 [           scanner][WebsocketServer][    INFO] consumer or producer of xxx stopped, cancelling pending tasks
`

**Comment by kduytsch** [comment]
We'd need at least an exception handling in order to: 
- know which device is causing the exception (and so we can diagnose on our side why the connection is terminated)
- perform a clean restart of the WS as apparently it goes in a strange state and a full restart is required (which makes loosing the pending queue)

**Comment by sn0opy** [comment]
There have been quite a few changes in dev that should result in proper errors or websocket handling in general. Please comment, if this problem persists.

**Comment by AndrewIammatteo** [comment]
I am also getting this issue pretty frequently. Websockets up to date
