### ISSUE TITLE
Statistic (quest) not working.

### ISSUE THREAD

**Issue by JabLuszko** [Map-A-Droid/MAD#148]
Going to Statistic in madmin renders no graphs - error below.
Just leaving it here if anyone ever decide to fix it without us changing sql_mode.
This is default MySQL setting.

```
 [03-30 00:32:05] [      Thread-839] [ dbWrapperBase:127] [   ERROR] Failed executing query: 1055 (42000): Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'database.trs_quest.quest_timestamp' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
 [03-30 00:32:05] [      Thread-839] [           app:1761] [   ERROR] Exception on /get_game_stats [GET]
Traceback (most recent call last):
  File "/home/mad/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mad/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mad/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mad/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mad/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mad/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mad/MAD/MAD/madmin/madmin.py", line 60, in decorated
    return func(*args, **kwargs)
  File "/home/mad/MAD/MAD/madmin/madmin.py", line 1356, in game_stats
    for dat in data:
TypeError: 'NoneType' object is not iterable
```

**Comment by cecpk** [comment]
SQL strict mode ... :D

**Comment by sn0opy** [comment]
Closed due to inactivity
