### ISSUE TITLE
Issue with rotate playerlvl on dev

### ISSUE THREAD

**Issue by clburlison** [Map-A-Droid/MAD#279]
https://github.com/Map-A-Droid/MAD/blob/b4e8b3f82384a50b96d2ae1aafa20fe109103267/worker/WorkerQuests.py#L351

```python
[07-22 11:11:37.48] [           moto01] [              start:66  ] [CRITICAL] Unhandled patched exception (<class 'TypeError'>): "get_playerlevel() missing 1 required positional argument: 'origin'".
Traceback (most recent call last):
  File "start.py", line 53, in run_thread
[07-22 11:11:37.48] [           moto01] [              start:66  ] [CRITICAL] Unhandled patched exception (<class 'TypeError'>): "get_playerlevel() missing 1 required positional argument: 'origin'".
    run_thread_old(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/worker/WorkerBase.py", line 411, in _main_work_thread
    self._post_move_location_routine(time_snapshot)
  File "/usr/src/app/worker/WorkerQuests.py", line 348, in _post_move_location_routine
    if self.get_devicesettings_value('rotate_on_lvl_30', False) and self._mitm_mapper.get_playerlevel() >= 30 \
  File "<string>", line 2, in get_playerlevel
  File "/usr/local/lib/python3.7/multiprocessing/managers.py", line 834, in _callmethod
    raise convert_to_error(kind, result)
TypeError: get_playerlevel() missing 1 required positional argument: 'origin'
```

I'm not actually familiar enough with the codebase to offer a PR at this time.

**Comment by cecpk** [comment]
pls retest - thx

**Comment by clburlison** [comment]
Verified as fixed. Thanks!
