### ISSUE TITLE
Crash due to screenshot ocr error (?) (latest dev as of now)

### ISSUE THREAD

**Issue by skofisk** [Map-A-Droid/MAD#303]
```
[07-30 03:09:20.50] [         s8walker] [           MITMBase:138 ] [    INFO] Worker s8walker is not injected till now (Count: 1)
[07-30 03:09:40.52] [         s8walker] [           MITMBase:138 ] [    INFO] Worker s8walker is not injected till now (Count: 2)
[07-30 03:10:00.55] [         s8walker] [           MITMBase:138 ] [    INFO] Worker s8walker is not injected till now (Count: 3)
[07-30 03:10:00.55] [         s8walker] [           MITMBase:141 ] [    INFO] Worker s8walker will retry check_windows while waiting for injection at count 3
[07-30 03:10:00.55] [         s8walker] [         WorkerBase:560 ] [    INFO] Checking pogo screen...
[07-30 03:10:09.79] [         Thread-9] [         screenPath:218 ] [    INFO] Processing Screen: ScreenType.RETRY
[07-30 03:10:26.09] [        Thread-10] [         screenPath:218 ] [    INFO] Processing Screen: ScreenType.RETURNING
[07-30 03:10:44.89] [         Thread-9] [         screenPath:218 ] [    INFO] Processing Screen: ScreenType.LOGINSELECT
[07-30 03:10:50.76] [        Thread-10] [         screenPath:218 ] [    INFO] Processing Screen: ScreenType.GGL
[07-30 03:10:50.76] [        Thread-10] [         screenPath:122 ] [    INFO] Request next Account - Using Nr. 1
[07-30 03:10:50.76] [        Thread-10] [         screenPath:134 ] [    INFO] Using GGL Account: po***on@***.org
[07-30 03:10:52.92] [        Thread-10] [         screenPath:478 ] [    INFO] Found mail po***on@***.org
[07-30 03:11:29.10] [         Thread-9] [         screenPath:218 ] [    INFO] Processing Screen: ScreenType.FAILURE
[07-30 03:11:35.77] [         s8walker] [         WorkerBase:580 ] [ WARNING] Something wrong with screendetection
[07-30 03:11:47.59] [        Thread-10] [         screenPath:218 ] [    INFO] Processing Screen: ScreenType.LOGINSELECT
[07-30 03:11:53.25] [         Thread-9] [         screenPath:218 ] [    INFO] Processing Screen: ScreenType.GGL
[07-30 03:11:53.25] [         Thread-9] [         screenPath:125 ] [    INFO] Request next Account - Restarting with Nr. 1
[07-30 03:11:53.25] [         Thread-9] [         screenPath:134 ] [    INFO] Using GGL Account: po***on@****.org
(<class 'xml.etree.ElementTree.ParseError'>, ParseError('syntax error: line 1, column 0',), <traceback object at 0x7fc6401f59c8>)
[07-30 03:11:54.78] [         s8walker] [              start:66  ] [CRITICAL] Unhandled patched exception (<class 'xml.etree.ElementTree.ParseError'>): "syntax error: line 1, column 0".
[07-30 03:11:54.78] [         s8walker] [              start:66  ] [CRITICAL] Unhandled patched exception (<class 'xml.etree.ElementTree.ParseError'>): "syntax error: line 1, column 0".
Traceback (most recent call last):
  File "start.py", line 53, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pokemon/MAD/worker/WorkerBase.py", line 321, in _main_work_thread
    self._internal_pre_work()
  File "/home/pokemon/MAD/worker/WorkerBase.py", line 271, in _internal_pre_work
    self._pre_work_loop()
  File "/home/pokemon/MAD/worker/WorkerQuests.py", line 77, in _pre_work_loop
    if not self._wait_for_injection() or self._stop_worker_event.is_set():
  File "/home/pokemon/MAD/worker/MITMBase.py", line 142, in _wait_for_injection
    self._check_windows()
  File "/home/pokemon/MAD/worker/WorkerBase.py", line 565, in _check_windows
    returncode = self._WordToScreenMatching.matchScreen()
  File "/home/pokemon/MAD/ocr/screenPath.py", line 165, in matchScreen
    return self.__thread_pool.apply_async(self.__internal_matchScreen, ()).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/pokemon/MAD/ocr/screenPath.py", line 223, in __internal_matchScreen
    if self.parse_ggl(self._communicator.uiautomator(), ggl_login.username):
  File "/home/pokemon/MAD/ocr/screenPath.py", line 475, in parse_ggl
    xmlroot = ET.fromstring(xml, parser=parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

**Comment by skofisk** [comment]
This is the "xml" it is trying to parse (I added an logger(xml))
`[07-30 19:42:11.34] [         Thread-9] [         screenPath:475 ] [    INFO] KO: Could not match typical hierarchy output: ERROR: null root node returned by UiTestAutomationBridge.`

**Comment by cecpk** [comment]
not fixed but add a retry
