### ISSUE TITLE
Timeout during init of worker CRITICAL kills RouteManager

### ISSUE THREAD

**Issue by JabLuszko** [Map-A-Droid/MAD#328]
```
[08-15 15:36:47.22] [             a95x] [         WorkerMITM:89  ] [    INFO] Walking roughly: 14.072936377982668
[08-15 15:36:49.05] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 15:36:48
[08-15 15:36:58.94] [             a95x] [         WorkerBase:253 ] [   ERROR] Timeout during init of worker a95x
[08-15 15:36:58.94] [             a95x] [         WorkerBase:302 ] [    INFO] Internal cleanup of a95x started
[08-15 15:36:58.94] [             a95x] [         WorkerBase:305 ] [    INFO] Internal cleanup of a95x signalling end to websocketserver
[08-15 15:36:58.94] [ MainProcess|a95x] [   RouteManagerBase:151 ] [    INFO] Worker a95x unregistering from routemanager RajdyWolaIOkolicePRIO
[08-15 15:36:58.94] [ MainProcess|a95x] [   RouteManagerBase:154 ] [    INFO] Cleanup routepool for origin a95x
[08-15 15:36:58.94] [             a95x] [       communicator:22  ] [    INFO] Communicator of a95x acquiring lock to cleanup worker in websocket
[08-15 15:36:58.95] [             a95x] [       communicator:25  ] [    INFO] Communicator of a95x calling cleanup
[08-15 15:36:58.95] [             a95x] [         WorkerBase:309 ] [    INFO] Stopped Route
[08-15 15:36:58.97] [             a95x] [         WorkerBase:316 ] [    INFO] Internal cleanup of a95x finished
[08-15 15:36:58.98] [      worker_a95x] [         WorkerBase:227 ] [    INFO] Worker a95x stopped gracefully
[08-15 15:36:59.05] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 15:36:58
[08-15 15:37:02.98] [             a95x] [           MITMBase:63  ] [    INFO] Waiting for data after 2019-08-15 15:36:45.957604
[08-15 15:37:03.99] [             a95x] [              start:66  ] [CRITICAL] Unhandled patched exception (<class 'KeyError'>): "'a95x'".
Traceback (most recent call last):
  File "start.py", line 53, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mad/MAD/worker/WorkerBase.py", line 411, in _main_work_thread
    self._post_move_location_routine(time_snapshot)
  File "/home/mad/MAD/worker/WorkerMITM.py", line 30, in _post_move_location_routine
    self._wait_for_data(timestamp)
  File "/home/mad/MAD/worker/MITMBase.py", line 124, in _wait_for_data
    self.worker_stats()
  File "/home/mad/MAD/worker/MITMBase.py", line 240, in worker_stats
    routemanager_status = self._mapping_manager.routemanager_get_route_stats(self._routemanager_name, self._id)
  File "<string>", line 2, in routemanager_get_route_stats
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'a95x'
[08-15 15:37:10.29] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 15:37:09
[08-15 15:37:40.62] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 15:37:39
and so on and so on.
```

avatar not moving, standing in one place. GMO still processed (from one place), so no auto-restart by MAD.  MAD full restart needed.

**Comment by cecpk** [comment]
Dev?

**Comment by JabLuszko** [comment]
> Dev?

Of course. It's random tho, only happen like once.

**Comment by JabLuszko** [comment]
```
[08-15 19:25:25.32] [ MainProcess|a95x] [   RouteManagerBase:529 ] [    INFO] RajdyWolaIOkolicePRIO: Moving on with location (x, y) [6 coords left (Workerpool) - 29 coords left (Route)]
[08-15 19:25:25.38] [             a95x] [         WorkerMITM:89  ] [    INFO] Walking roughly: 14.071051102067212
[08-15 19:25:26.87] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 19:25:25
[08-15 19:25:37.82] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 19:25:36
[08-15 19:25:41.08] [             a95x] [           MITMBase:63  ] [    INFO] Waiting for data after 2019-08-15 19:25:23.183094
[08-15 19:25:42.17] [             a95x] [         WorkerBase:417 ] [    INFO] Worker a95x finished iteration, continuing work
[08-15 19:25:42.36] [ MainProcess|a95x] [   RouteManagerBase:529 ] [    INFO] RajdyWolaIOkolicePRIO: Moving on with location (x, y) [5 coords left (Workerpool) - 29 coords left (Route)]
[08-15 19:25:42.46] [             a95x] [         WorkerMITM:89  ] [    INFO] Walking roughly: 14.07082335722052
[08-15 19:25:46.78] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 19:25:46
[08-15 19:25:56.83] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 19:25:55
[08-15 19:25:58.22] [             a95x] [           MITMBase:63  ] [    INFO] Waiting for data after 2019-08-15 19:25:40.169433
[08-15 19:25:59.32] [             a95x] [         WorkerBase:417 ] [    INFO] Worker a95x finished iteration, continuing work
[08-15 19:25:59.48] [ MainProcess|a95x] [   RouteManagerBase:529 ] [    INFO] RajdyWolaIOkolicePRIO: Moving on with location (x, y) [4 coords left (Workerpool) - 21 coords left (Route)]
[08-15 19:25:59.53] [             a95x] [         WorkerMITM:89  ] [    INFO] Walking roughly: 14.071233068882135
[08-15 19:26:07.29] [          scanner] [    WebsocketServer:165 ] [    INFO] Client a95x registering
[08-15 19:26:07.29] [          scanner] [    WebsocketServer:202 ] [ WARNING] Worker with origin a95x is already running, killing the running one and have client reconnect
[08-15 19:26:07.29] [          scanner] [         WorkerBase:236 ] [ WARNING] Worker a95x stop called
[08-15 19:26:10.38] [          scanner] [    WebsocketServer:165 ] [    INFO] Client a95x registering
[08-15 19:26:10.38] [          scanner] [    WebsocketServer:202 ] [ WARNING] Worker with origin a95x is already running, killing the running one and have client reconnect
[08-15 19:26:10.39] [          scanner] [         WorkerBase:236 ] [ WARNING] Worker a95x stop called
[08-15 19:26:13.47] [          scanner] [    WebsocketServer:165 ] [    INFO] Client a95x registering
[08-15 19:26:13.47] [          scanner] [    WebsocketServer:202 ] [ WARNING] Worker with origin a95x is already running, killing the running one and have client reconnect
[08-15 19:26:13.47] [          scanner] [         WorkerBase:236 ] [ WARNING] Worker a95x stop called
[08-15 19:26:14.16] [          scanner] [    WebsocketServer:426 ] [ WARNING] Connection to a95x was closed, stopping worker
[08-15 19:26:14.16] [          scanner] [         WorkerBase:236 ] [ WARNING] Worker a95x stop called
[08-15 19:26:14.16] [          scanner] [    WebsocketServer:153 ] [    INFO] consumer or producer of a95x stopped, cancelling pending tasks
[08-15 19:26:14.16] [          scanner] [    WebsocketServer:157 ] [    INFO] Awaiting unregister of a95x
[08-15 19:26:14.16] [          scanner] [         WorkerBase:236 ] [ WARNING] Worker a95x stop called
[08-15 19:26:14.16] [          scanner] [    WebsocketServer:370 ] [    INFO] Worker a95x unregistered
[08-15 19:26:14.17] [          scanner] [    WebsocketServer:160 ] [    INFO] All done with a95x
[08-15 19:26:16.56] [          scanner] [    WebsocketServer:165 ] [    INFO] Client a95x registering
[08-15 19:26:16.56] [          scanner] [    WebsocketServer:215 ] [    INFO] Starting worker a95x
[08-15 19:26:16.56] [          scanner] [    WebsocketServer:231 ] [    INFO] Setting up routemanagers for a95x
[08-15 19:26:16.57] [          scanner] [    WebsocketServer:290 ] [    INFO] a95x using walker area RajdyWolaIOkolicePRIO [26/28]
[08-15 19:26:16.57] [          scanner] [         WorkerBase:77  ] [    INFO] a95x: last Mode not pokestop - reset saved location
[08-15 19:26:16.59] [          scanner] [    WebsocketServer:417 ] [    INFO] Consumer handler of a95x starting
[08-15 19:26:16.60] [             a95x] [         WorkerBase:245 ] [    INFO] Setting startcoords or walker lat 52.231713 / lng 20.948372
[08-15 19:26:16.78] [             a95x] [         WorkerBase:549 ] [    INFO] turnScreenOnAndStartPogo: (Re-)Starting Pogo
[08-15 19:26:17.02] [             a95x] [         WorkerBase:260 ] [    INFO] Try to register a95x in Routemanager RajdyWolaIOkolicePRIO
[08-15 19:26:17.02] [ MainProcess|a95x] [   RouteManagerBase:132 ] [    INFO] Worker a95x already registered to routemanager RajdyWolaIOkolicePRIO
[08-15 19:26:17.02] [             a95x] [         WorkerMITM:125 ] [    INFO] MITM worker starting
[08-15 19:26:17.17] [ MainProcess|a95x] [   RouteManagerBase:529 ] [    INFO] RajdyWolaIOkolicePRIO: Moving on with location (x, y) [3 coords left (Workerpool) - 5 coords left (Route)]
[08-15 19:26:17.25] [             a95x] [         WorkerMITM:89  ] [    INFO] Walking roughly: 14.07148454872795
[08-15 19:26:19.75] [             a95x] [    WebsocketServer:570 ] [   ERROR] Worker a95x was removed, propagating exception
[08-15 19:26:19.75] [             a95x] [         WorkerBase:397 ] [ WARNING] Worker a95x failed moving to new location, stopping worker, connection terminated exceptionally
[08-15 19:26:19.75] [             a95x] [         WorkerBase:302 ] [    INFO] Internal cleanup of a95x started
[08-15 19:26:19.75] [             a95x] [         WorkerBase:305 ] [    INFO] Internal cleanup of a95x signalling end to websocketserver
[08-15 19:26:19.75] [ MainProcess|a95x] [   RouteManagerBase:151 ] [    INFO] Worker a95x unregistering from routemanager RajdyWolaIOkolicePRIO
[08-15 19:26:19.75] [ MainProcess|a95x] [   RouteManagerBase:154 ] [    INFO] Cleanup routepool for origin a95x
[08-15 19:26:19.75] [             a95x] [       communicator:22  ] [    INFO] Communicator of a95x acquiring lock to cleanup worker in websocket
[08-15 19:26:19.76] [             a95x] [       communicator:25  ] [    INFO] Communicator of a95x calling cleanup
[08-15 19:26:19.76] [             a95x] [         WorkerBase:309 ] [    INFO] Stopped Route
[08-15 19:26:19.76] [             a95x] [         WorkerBase:312 ] [    INFO] Stopping worker's asyncio loop
[08-15 19:26:19.76] [             a95x] [         WorkerBase:316 ] [    INFO] Internal cleanup of a95x finished
[08-15 19:26:19.76] [      worker_a95x] [         WorkerBase:227 ] [    INFO] Worker a95x stopped gracefully
[08-15 19:26:32.98] [             a95x] [           MITMBase:63  ] [    INFO] Waiting for data after 2019-08-15 19:26:16.999995
[08-15 19:26:52.59] [             a95x] [           MITMBase:95  ] [ WARNING] Timeout waiting for data
[08-15 19:26:52.59] [             a95x] [              start:66  ] [CRITICAL] Unhandled patched exception (<class 'KeyError'>): "'a95x'".
[08-15 19:27:17.94] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 19:27:17
[08-15 19:27:18.75] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 19:27:18
[08-15 19:27:50.65] [       MainThread] [  MITMDataProcessor:68  ] [ SUCCESS] Processing GMO received from a95x. Received at 2019-08-15 19:27:49

```

**Comment by sn0opy** [comment]
Does this issue still occur? Feel free to reopen the issue in case it does.
