### ISSUE TITLE
KeyError: 'level'

### ISSUE THREAD

**Issue by simonbuehler** [Map-A-Droid/MAD#601]
hi,
get this trace when trying to select account

```
-10 00:06:31.12] [            s7neu] [           MITMBase:144 ] [    INFO] PogoDroid on worker s7neu didn't connect yet. Probably not injected? (Count: 3/20)
[12-10 00:06:31.12] [            s7neu] [           MITMBase:147 ] [    INFO] Worker s7neu will retry check_windows while waiting for injection at count 3
[12-10 00:06:31.12] [            s7neu] [         WorkerBase:568 ] [    INFO] Checking pogo screen...
[12-10 00:06:34.92] [   webhook_worker] [      webhookworker:138 ] [ SUCCESS] Successfully sent payload to webhook. Stats: {"pokemon": 5}
[12-10 00:06:37.46] [            s7neu] [         screenPath:194 ] [    INFO] Processing Screen: ScreenType.RETURNING
[12-10 00:06:43.82] [               s7] [           MITMBase:144 ] [    INFO] PogoDroid on worker s7 didn't connect yet. Probably not injected? (Count: 0/20)
[12-10 00:06:44.66] [            s7neu] [         screenPath:194 ] [    INFO] Processing Screen: ScreenType.LOGINSELECT
[12-10 00:06:44.66] [            s7neu] [              start:61  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f048a660d90>
    └ <Thread(s7neu, started daemon 139655685072640)>
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x7f04632d4598>
    └ <Thread(s7neu, started daemon 139655685072640)>

> File "start.py", line 55, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(s7neu, started daemon 139655685072640)>,)
    └ <function Thread.run at 0x7f048a660b70>

  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │             │             └ <Thread(s7neu, started daemon 139655685072640)>
    │             └ <Thread(s7neu, started daemon 139655685072640)>
    └ <Thread(s7neu, started daemon 139655685072640)>

  File "/var/www/www.xxx.xx/MAD/worker/WorkerBase.py", line 319, in _main_work_thread
    self._internal_pre_work()
    │    └ <function WorkerBase._internal_pre_work at 0x7f046334dbf8>
    └ <worker.WorkerQuests.WorkerQuests object at 0x7f04382f9fd0>

  File "/var/www/www.xxx.xx/MAD/worker/WorkerBase.py", line 268, in _internal_pre_work
    self._pre_work_loop()
    │    └ <function WorkerQuests._pre_work_loop at 0x7f04632d3730>
    └ <worker.WorkerQuests.WorkerQuests object at 0x7f04382f9fd0>

  File "/var/www/www.xxx.xx/MAD/worker/WorkerQuests.py", line 81, in _pre_work_loop
    if not self._wait_for_injection() or self._stop_worker_event.is_set():
           │    │                        │    │                  └ <function Event.is_set at 0x7f048a65ef28>
           │    │                        │    └ <threading.Event object at 0x7f04382f9ba8>
           │    │                        └ <worker.WorkerQuests.WorkerQuests object at 0x7f04382f9fd0>
           │    └ <function MITMBase._wait_for_injection at 0x7f04632d0620>
           └ <worker.WorkerQuests.WorkerQuests object at 0x7f04382f9fd0>

  File "/var/www/www.xxx.xx/MAD/worker/MITMBase.py", line 148, in _wait_for_injection
    self._check_windows()
    │    └ <function WorkerBase._check_windows at 0x7f04632d1400>
    └ <worker.WorkerQuests.WorkerQuests object at 0x7f04382f9fd0>

  File "/var/www/www.xxx.xx/MAD/worker/WorkerBase.py", line 573, in _check_windows
    returncode = self._WordToScreenMatching.matchScreen()
                 │    │                     └ <function WordToScreenMatching.matchScreen at 0x7f0463341a60>
                 │    └ <ocr.screenPath.WordToScreenMatching object at 0x7f04382f9b70>
                 └ <worker.WorkerQuests.WorkerQuests object at 0x7f04382f9fd0>

  File "/var/www/www.xxx.xx/MAD/ocr/screenPath.py", line 312, in matchScreen
    n_boxes = len(globaldict['level'])
                  └ {}

KeyError: 'level'
[12-10 00:06:44.66] [            s7neu] [              start:61  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
> File "start.py", line 55, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/www.xxx.xx/MAD/worker/WorkerBase.py", line 319, in _main_work_thread
    self._internal_pre_work()
  File "/var/www/www.xxx.xx/MAD/worker/WorkerBase.py", line 268, in _internal_pre_work
    self._pre_work_loop()
  File "/var/www/www.xxx.xx/MAD/worker/WorkerQuests.py", line 81, in _pre_work_loop
    if not self._wait_for_injection() or self._stop_worker_event.is_set():
  File "/var/www/www.xxx.xx/MAD/worker/MITMBase.py", line 148, in _wait_for_injection
    self._check_windows()
  File "/var/www/www.xxx.xx/MAD/worker/WorkerBase.py", line 573, in _check_windows
    returncode = self._WordToScreenMatching.matchScreen()
  File "/var/www/www.xxx.xx/MAD/ocr/screenPath.py", line 312, in matchScreen
    n_boxes = len(globaldict['level'])
KeyError: 'level'`
```

**Comment by cecpk** [comment]
fixed on master
