### ISSUE TITLE
Worker kinda dies 

### ISSUE THREAD

**Issue by muckelba** [Map-A-Droid/MAD#684]
Hey, im not sure if thats exclusive to leveling but sometime a worker dies out of nowhere with following exception:
```
[01-14 04:27:18.37] [         box3] [              start:61  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
> File "start.py", line 55, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pokemon/level/MAD/worker/WorkerBase.py", line 357, in _main_work_thread
    settings = self._internal_grab_next_location()
  File "/home/pokemon/level/MAD/worker/WorkerBase.py", line 522, in _internal_grab_next_location
    self.current_location = self._mapping_manager.routemanager_get_next_location(self._routemanager_name, self._id)
  File "<string>", line 2, in routemanager_get_next_location
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
RuntimeError: dictionary changed size during iteration
```

RGC and PD are still running and i can see the device in device control, but MAD never comunicates again with it until a MAD or device restart.

**Comment by marcb1387** [comment]
i experienced this as well with a long walker route i was able to roll back to an earlier build to not have those issues. walker route was 21 stops. on a device that only had 1 route it seems to work fine but the longer one died.

**Comment by muckelba** [comment]
commit 8d972d34fb599d740afb0c2b413b5229bf1dc1ab seems to have fixed that. Can you test it @marcb1387 ?

**Comment by muckelba** [comment]
Closing this since i never had that issue again
