### ISSUE TITLE
Workers stop working and never start again...

### ISSUE THREAD

**Issue by wraythex** [Map-A-Droid/MAD#714]
I updated mad earlier today, and then applied PR712 so that my db would update properly.  Once I started mad all my devices started working like they normally do.  However, eventually, 2 (then later, 4) devices just stopped working in the middle of their raid routes.  And they never started that route again.  This never happened on previous branches.  Speaking of, I'm not sure which version I was on prior to today's pull.  Here is my recent git log:
$ git log --oneline -5
11ca047 (HEAD -> tmp_pr) Several patcher fixes
838f593 (origin/master, origin/HEAD, master) Reduce loglevel of list vs dict distinction in MITMReceiver
620f1a4 Fix configmode
9a94700 Websocket rework (#705)
18c6e9d Add MAD Default jobs to command.json

I'm including (anonymized) logs from one of my devices and the server log (no -v), both from 10 minutes before the problem started to 15 minutes after the problem started.  I also just noticed that it is now a new day and the status shows as still being on yesterday's raid route, and they haven't switched over to quest scanning like the still-working devices have.

Manually rebooting (unplugging the power, waiting a minute, then re-plugging the power) the non-working devices gives the following in madmin:
[01-27 00:22:11.01] [          scanner] [    WebsocketServer:319 ] [ WARNING] Connection of atv101 closed in __client_message_receiver
[01-27 00:22:11.01] [          scanner] [    WebsocketServer:234 ] [    INFO] Awaiting unregister of atv101
[01-27 00:22:11.06] [          scanner] [    WebsocketServer:237 ] [    INFO] Done with connection from atv101 (('ip-address', 47138))
[01-27 00:23:32.78] [          scanner] [    WebsocketServer:278 ] [    INFO] Client atv101 registering
[01-27 00:23:32.78] [          scanner] [    WebsocketServer:167 ] [    INFO] New connection with origin atv101 from ('ip-address', 40706)
[01-27 00:23:32.78] [          scanner] [    WebsocketServer:190 ] [    INFO] There is a worker thread entry for atv101 present, handling accordingly
[01-27 00:23:32.78] [          scanner] [    WebsocketServer:199 ] [    INFO] Worker thread of atv101 still alive, continue as usual
[01-27 00:23:32.79] [          scanner] [    WebsocketServer:303 ] [    INFO] Consumer handler of atv101 starting
[01-27 00:24:33.11] [          scanner] [    WebsocketServer:319 ] [ WARNING] Connection of atv101 closed in __client_message_receiver
[01-27 00:24:33.11] [          scanner] [    WebsocketServer:234 ] [    INFO] Awaiting unregister of atv101
[01-27 00:24:33.11] [          scanner] [    WebsocketServer:237 ] [    INFO] Done with connection from atv101 (('ip-address', 40706))
[01-27 00:27:18.34] [          scanner] [    WebsocketServer:278 ] [    INFO] Client atv101 registering
[01-27 00:27:18.34] [          scanner] [    WebsocketServer:167 ] [    INFO] New connection with origin atv101 from ('ip-address', 52415)
[01-27 00:27:18.34] [          scanner] [    WebsocketServer:190 ] [    INFO] There is a worker thread entry for atv101 present, handling accordingly
[01-27 00:27:18.34] [          scanner] [    WebsocketServer:199 ] [    INFO] Worker thread of atv101 still alive, continue as usual
[01-27 00:27:18.34] [          scanner] [    WebsocketServer:303 ] [    INFO] Consumer handler of atv101 starting

Then there were no more messages (5 minutes later) about the device, like mad just gave up on these devices.  I just restarted mad and now all devices are working on quests as expected.  But, since this also happened earlier today, it seems it is only a matter of time until some devices stop working again.  Please let me know if I can provide any additional information in regards to this problem.

[output101-dev.txt](https://github.com/Map-A-Droid/MAD/files/4115764/output101-dev.txt)
[output101-srv.txt](https://github.com/Map-A-Droid/MAD/files/4115765/output101-srv.txt)

**Comment by boby360** [comment]
I had the same issue with a fully up to date master branch. No #712. I was attempting to do updates which seem to have issues. A restart of mad corrected whatever issue it had. Randomly dead in the water devices worked.

**Comment by Grennith** [comment]
Would you mind uploading a debug log?

**Comment by Seandals** [comment]
I also ran into this issue tonight as well. I don't have full logs but I'll provide what I have. I was completing my nightly quest run when one of my devices stopped responding for an unknown reason. Even power cycling the ATV would not cause it to start working again, only a restart of MAD itself.

After a power cycle, the ATV would reconnect but would not launch pogo as normal. Launching pogo through scrcpy provided no fix either. Below is the information from the terminal. This is all that ever appears after a power cycle from the down worker (no normal waiting for injection, etc)

```
[01-27 05:03:14.44] [          scanner] [    WebsocketServer:278 ] [    INFO] Client Four registering
[01-27 05:03:14.44] [          scanner] [    WebsocketServer:167 ] [    INFO] New connection with origin Four from ('REDACTED', 48250)
[01-27 05:03:14.44] [          scanner] [    WebsocketServer:190 ] [    INFO] There is a worker thread entry for Four present, handling accordingly
[01-27 05:03:14.44] [          scanner] [    WebsocketServer:193 ] [   ERROR] Old connection open while a new one is attempted to be established, aborting handling of connection from Four
[01-27 05:03:14.44] [          scanner] [    WebsocketServer:193 ] [   ERROR] Old connection open while a new one is attempted to be established, aborting handling of connection from Four
[01-27 05:03:14.44] [          scanner] [    WebsocketServer:199 ] [    INFO] Worker thread of Four still alive, continue as usual
[01-27 05:03:21.59] [          scanner] [    WebsocketServer:313 ] [ WARNING] Connection to Four was closed, stopping receiver. Exception:
[01-27 05:03:21.59] [          scanner] [    WebsocketServer:234 ] [    INFO] Awaiting unregister of Four
[01-27 05:03:21.60] [          scanner] [    WebsocketServer:237 ] [    INFO] Done with connection from Four (('REDACTED', 47095))
[01-27 05:03:22.13] [worker_join_thread] [    WebsocketServer:139 ] [    INFO] Trying to join worker thread
[01-27 05:03:24.54] [          scanner] [    WebsocketServer:278 ] [    INFO] Client Four registering
[01-27 05:03:24.54] [          scanner] [    WebsocketServer:167 ] [    INFO] New connection with origin Four from ('REDACTED', 48257)
[01-27 05:03:24.54] [          scanner] [    WebsocketServer:190 ] [    INFO] There is a worker thread entry for Four present, handling accordingly
[01-27 05:03:24.54] [          scanner] [    WebsocketServer:199 ] [    INFO] Worker thread of Four still alive, continue as usual
```

I was able to reproduce the below errors several times by attempting to reboot the device using the Devicecontrol tab in MADmin. Pushing the Reboot Device button from the Devicecontrol page led to a browser internal server error.

`
[01-27 05:04:01.02] [       Thread-353] [             madmin:33  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./start.py", line 56, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 327, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 362, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/MAD/mapadroid/madmin/reverseproxy.py", line 22, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
> File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/MAD/mapadroid/madmin/functions.py", line 31, in decorated
    return func(*args, **kwargs)
  File "/root/MAD/mapadroid/madmin/routes/control.py", line 305, in restart_phone
    self._ws_server.force_disconnect(origin)
AttributeError: 'WebsocketServer' object has no attribute 'force_disconnect'
`
and

```
[01-27 05:04:01.02] [       Thread-353] [             madmin:33  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fafc1fb7ea0>
    └ <Thread(Thread-353, started daemon 140390938048256)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x7fafb6720950>
    └ <Thread(Thread-353, started daemon 140390938048256)>

  File "./start.py", line 56, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(Thread-353, started daemon 140390938048256)>,)
    └ <function Thread.run at 0x7fafc1fb7c80>

  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-353, started daemon 140390938048256)>
    │    │        │    └ (<socket.socket fd=33, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5050), raddr=(...
    │    │        └ <Thread(Thread-353, started daemon 140390938048256)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x7fafa8654f98>>
    └ <Thread(Thread-353, started daemon 140390938048256)>
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 54688)
    │    │              └ <socket.socket fd=33, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5050), raddr=('...
    │    └ <function BaseServer.finish_request at 0x7fafb544c048>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7fafa8654f98>
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x7fafa8654f98>
    │    │                   │        └ ('127.0.0.1', 54688)
    │    │                   └ <socket.socket fd=33, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5050), raddr=('...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7fafa8654f98>
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7fafb53f80d0>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7fafa83e09e8>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 327, in handle
    rv = BaseHTTPRequestHandler.handle(self)
         │                      │      └ <werkzeug.serving.WSGIRequestHandler object at 0x7fafa83e09e8>
         │                      └ <function BaseHTTPRequestHandler.handle at 0x7fafb54509d8>
         └ <class 'http.server.BaseHTTPRequestHandler'>

  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7fafb53f8268>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7fafa83e09e8>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 362, in handle_one_request
    return self.run_wsgi()
           │    └ <function WSGIRequestHandler.run_wsgi at 0x7fafb53f8048>
           └ <werkzeug.serving.WSGIRequestHandler object at 0x7fafa83e09e8>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 304, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <Flask 'mapadroid.madmin.madmin'>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7fafa8654f98>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x7fafa83e09e8>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x7fafa81e86a8>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 292, in execute
    application_iter = app(environ, start_response)
                       │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7faf644bc158>
                       │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=33>, 'wsgi.errors': <_io.TextIOWra...
                       └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7faf644bc158>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=33>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <mapadroid.madmin.reverseproxy.ReverseProxied object at 0x7fafa874bd30>
           └ <Flask 'mapadroid.madmin.madmin'>

  File "/root/MAD/mapadroid/madmin/reverseproxy.py", line 22, in __call__
    return self.app(environ, start_response)
           │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7faf644bc158>
           │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=33>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <werkzeug.middleware.proxy_fix.ProxyFix object at 0x7fafa8736160>
           └ <mapadroid.madmin.reverseproxy.ReverseProxied object at 0x7fafa874bd30>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
           │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7faf644bc158>
           │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=33>, 'wsgi.errors': <_io.TextIOWra...
           │    └ <bound method Flask.wsgi_app of <Flask 'mapadroid.madmin.madmin'>>
           └ <werkzeug.middleware.proxy_fix.ProxyFix object at 0x7fafa8736160>

> File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x7fafb505b8c8>
               └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
         │    └ <function Flask.handle_user_exception at 0x7fafb505b620>
         └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    │       │         │          └ <traceback object at 0x7faf4d174308>
    │       │         └ AttributeError("'WebsocketServer' object has no attribute 'force_disconnect'",)
    │       └ <class 'AttributeError'>
    └ <function reraise at 0x7fafb5351378>

  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
          └ AttributeError("'WebsocketServer' object has no attribute 'force_disconnect'",)

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x7fafb505b840>
         └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
           │    │              │    │           │   └ {}
           │    │              │    │           └ <Request 'http://REDACTED/restart_phone?origin=Four&adb=False' [GET]>
           │    │              │    └ 'restart_phone'
           │    │              └ <Rule '/restart_phone' (OPTIONS, HEAD, POST, GET) -> restart_phone>
           │    └ {'static': <bound method _PackageBoundObject.send_static_file of <Flask 'mapadroid.madmin.madmin'>>, 'statistics': <bound met...
           └ <Flask 'mapadroid.madmin.madmin'>

  File "/root/MAD/mapadroid/madmin/functions.py", line 31, in decorated
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<mapadroid.madmin.routes.control.control object at 0x7fafa875d5f8>,)
           └ <function control.restart_phone at 0x7fafa87108c8>

  File "/root/MAD/mapadroid/madmin/routes/control.py", line 305, in restart_phone
    self._ws_server.force_disconnect(origin)
    │    │                           └ 'Four'
    │    └ <mapadroid.websocket.WebsocketServer.WebsocketServer object at 0x7fafaa09fc88>
    └ <mapadroid.madmin.routes.control.control object at 0x7fafa875d5f8>

AttributeError: 'WebsocketServer' object has no attribute 'force_disconnect'

```

Hope this helps.

**Comment by Seandals** [comment]
Just a little more info as I realized I have 2GB of MAD logs on my server.... cripes....

I restarted my server at 04:30 and for the next 11 minutes the worker went through the "didn't connect, probably not injected" phase. The worker was working normally at the time of the restart.

[01-27 04:41:55.26] [             Four] [           MITMBase:169 ] [    INFO] PogoDroid on worker Four didn't connect yet. Probably not injected? (Count: 14/20)
[01-27 04:42:11.54] [          scanner] [    WebsocketServer:319 ] [ WARNING] Connection of Four closed in __client_message_receiver
[01-27 04:42:11.54] [          scanner] [    WebsocketServer:234 ] [    INFO] Awaiting unregister of Four
[01-27 04:42:11.55] [          scanner] [    WebsocketServer:237 ] [    INFO] Done with connection from Four (('REDACTED', 41179))
[01-27 04:42:11.95] [worker_join_thread] [    WebsocketServer:139 ] [    INFO] Trying to join worker thread
[01-27 04:42:15.30] [             Four] [           MITMBase:169 ] [    INFO] PogoDroid on worker Four didn't connect yet. Probably not injected? (Count: 15/20)
[01-27 04:42:15.30] [             Four] [           MITMBase:172 ] [    INFO] Worker Four will retry check_windows while waiting for injection at count 15
[01-27 04:42:15.30] [             Four] [         WorkerBase:582 ] [    INFO] Checking pogo screen...

[01-27 04:43:20.91] [          scanner] [    WebsocketServer:278 ] [    INFO] Client Four registering
[01-27 04:43:20.91] [          scanner] [    WebsocketServer:167 ] [    INFO] New connection with origin Four from ('REDACTED', 47497)
[01-27 04:43:20.92] [          scanner] [    WebsocketServer:190 ] [    INFO] There is a worker thread entry for Four present, handling accordingly
[01-27 04:43:20.92] [          scanner] [    WebsocketServer:199 ] [    INFO] Worker thread of Four still alive, continue as usual
[01-27 04:43:20.92] [          scanner] [    WebsocketServer:303 ] [    INFO] Consumer handler of Four starting
[01-27 04:43:25.71] [          scanner] [    WebsocketServer:278 ] [    INFO] Client Four registering
[01-27 04:43:25.71] [          scanner] [    WebsocketServer:167 ] [    INFO] New connection with origin Four from ('REDACTED', 56581)
[01-27 04:43:25.72] [          scanner] [    WebsocketServer:190 ] [    INFO] There is a worker thread entry for Four present, handling accordingly
[01-27 04:43:25.72] [          scanner] [    WebsocketServer:193 ] [   ERROR] Old connection open while a new one is attempted to be established, aborting handling of connection from Four
[01-27 04:43:25.72] [          scanner] [    WebsocketServer:199 ] [    INFO] Worker thread of Four still alive, continue as usual
[01-27 04:43:36.44] [          scanner] [    WebsocketServer:313 ] [ WARNING] Connection to Four was closed, stopping receiver. Exception: 
[01-27 04:43:38.82] [          scanner] [    WebsocketServer:278 ] [    INFO] Client Four registering
[01-27 04:43:38.82] [          scanner] [    WebsocketServer:167 ] [    INFO] New connection with origin Four from ('REDACTED', 56592)
[01-27 04:43:38.82] [          scanner] [    WebsocketServer:190 ] [    INFO] There is a worker thread entry for Four present, handling accordingly
[01-27 04:43:38.82] [          scanner] [    WebsocketServer:199 ] [    INFO] Worker thread of Four still alive, continue as usual
[01-27 04:43:38.83] [          scanner] [    WebsocketServer:303 ] [    INFO] Consumer handler of Four starting

From this point on, the worker has no further communication with MAD. Even when the ATV is powercycled, it makes contact with MAD in the above manner and just sits.

**Comment by gcm-explo1t** [comment]
+1

**Comment by myGamecodescom** [comment]
+1

**Comment by Grennith** [comment]
> +1
> Yesterday 2 Devices stop working
> Today the next 2 Devices stop working

Cool, I am still waiting for debug logs.

**Comment by myGamecodescom** [comment]
I have update today and now all boxes are working.
I also have write an Logfile, i post it on Discord, because the file is too big.

**Comment by sn0opy** [comment]
> I also have write an Logfile, i post it on Discord, because the file is too big.

Please post the link to the message here, otherwise there's no way to get a reference between your comment and your message on Discord ...

**Comment by myGamecodescom** [comment]
https://cdn.discordapp.com/attachments/467318166620471296/671659292616556557/20200128_0945_mad.2020-01-28_10-51-03_934124.log

**Comment by ChaosEmpire** [comment]
-vv log transfered to grennith

**Comment by Grennith** [comment]
Please pull 45a08bf2c4a7b22699d1dc69eef1280acadf8119 and report back

**Comment by Markus1589** [comment]
Had the same issue yesterday, the fix today worked for me. Great Work.

**Comment by wraythex** [comment]
Over 24 hours with yesterday's fix and no more stalled workers.  Fix is in master so anyone with this issue can git pull to get the patch.
