### ISSUE TITLE
Exception while Apply Settings

### ISSUE THREAD

**Issue by spammer23** [Map-A-Droid/MAD#717]
Getting the following Error every ~5 reloads.
Page loads for ever and throws a 500 error at the end.

https://pastebin.com/BTkrBUJc
Newest Pull

**Comment by sn0opy** [comment]
Can you still replicate this issue?

**Comment by spammer23** [comment]
Did a Pull now, will test tomorrow.

**Comment by spammer23** [comment]
Still get an Error:
https://pastebin.com/shswHAMU

**Comment by spammer23** [comment]
New Error when hitting Apply Settings
Press it 3 times and it works

```
[2020-07-31 17:41:48,942] ERROR in app: Exception on /reload [GET]
Traceback (most recent call last):
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/MAD/mapadroid/madmin/functions.py", line 25, in decorated
    return func(*args, **kwargs)
  File "/opt/MAD/mapadroid/madmin/routes/config.py", line 406, in reload
    self._mapping_mananger.update()
  File "<string>", line 2, in update
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
AttributeError: 'NoneType' object has no attribute 'join'
```

**Comment by spammer23** [comment]
Still same error
```[2021-04-28 23:54:15,238] ERROR in app: Exception on /reload [GET]
Traceback (most recent call last):
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pokeuser/mad_env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/MAD/mapadroid/madmin/functions.py", line 24, in decorated
    return func(*args, **kwargs)
  File "/opt/MAD/mapadroid/madmin/routes/config.py", line 451, in reload
    self._mapping_mananger.update()
  File "<string>", line 2, in update
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
AttributeError: 'NoneType' object has no attribute 'join'
