### ISSUE TITLE
Starting RGC without PoGodroid and reboot True results in an Error

### ISSUE THREAD

**Issue by C64Axel** [Map-A-Droid/MAD#73]
Hi.

When i start RGC and Parameter reboot is true, i get an Error after Message "Timeout waiting for data"
PogODroid is not started.
reboot_thresh is set to 2

[02-10 18:20:26] [         scanner] [WebsocketServer:67] [    INFO] Waiting for connection...
 [02-10 18:20:26] [         scanner] [WebsocketServer:92] [    INFO] Client s5mini1 registering
 [02-10 18:20:26] [         scanner] [         timer:17] [    INFO] [s5mini1] - check for Switchtimer
 [02-10 18:20:26] [     switchtimer] [         timer:34] [    INFO] [s5mini1] - Starting Switchtimer
 [02-10 18:20:27] [         scanner] [WebsocketServer:226] [ WARNING] Consumer handler of s5mini1 starting
 [02-10 18:20:27] [         s5mini1] [    WorkerBase:352] [ WARNING] turnScreenOnAndStartPogo: (Re-)Starting Pogo
 [02-10 18:20:29] [         s5mini1] [    WorkerMITM:114] [ WARNING] startPogo: Starting pogo...
 [02-10 18:21:29] [         s5mini1] [    WorkerMITM:93] [    INFO] MITM worker starting
 [02-10 18:21:29] [         s5mini1] [RouteManagerBase:242] [    INFO] Round of route Hockenheim is moving to 49.414038, 8.52543 for a priority event
 [02-10 18:21:29] [         s5mini1] [RouteManagerBase:279] [    INFO] Hockenheim done grabbing next coord, releasing lock and returning location: 49.414038, 8.52543
 [02-10 18:21:29] [         s5mini1] [    WorkerMITM:39] [    INFO] main: Moving 5556401.284728093 meters to the next position
 [02-10 18:21:29] [         s5mini1] [    WorkerMITM:47] [    INFO] main: Teleporting...
 [02-10 18:21:29] [         s5mini1] [    WorkerMITM:60] [    INFO] Need more sleep after Teleport: 8 seconds!
 [02-10 18:21:29] [         s5mini1] [    WorkerMITM:69] [    INFO] Walking a bit: 13.269789513563467
 [02-10 18:21:38] [         s5mini1] [    WorkerMITM:85] [    INFO] Sleeping 8
 [02-10 18:21:46] [         s5mini1] [    WorkerMITM:168] [    INFO] Waiting for data after 1549819289, error count is at 0
 [02-10 18:23:00] [         s5mini1] [    WorkerMITM:249] [ WARNING] Timeout waiting for data
Exception in thread s5mini1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/MAD/worker/WorkerBase.py", line 286, in _main_work_thread
    self._post_move_location_routine(time_snapshot)
  File "/root/MAD/worker/WorkerMITM.py", line 28, in _post_move_location_routine
    self.__wait_for_data(timestamp)
  File "/root/MAD/worker/WorkerMITM.py", line 258, in __wait_for_data
    and self.__reboot_count > self._devicesettings.get("reboot_thresh", 5)
AttributeError: 'WorkerMITM' object has no attribute '_WorkerMITM__reboot_count'

**Comment by Grennith** [comment]
Are you sure you are up to date?

**Comment by C64Axel** [comment]
Yes. Server RGC and PoGoDroid

**Comment by Grennith** [comment]
/blame cec
https://github.com/Map-A-Droid/MAD/blame/4ffc0cc814ff419a1c261fe2288f52d593c86681/worker/WorkerMITM.py#L258

I adjusted some stuff, should be good to go now
