### ISSUE TITLE
Issue  ValueError: invalid literal for int()

### ISSUE THREAD

**Issue by Mystic018** [Map-A-Droid/MAD#762]
Hi, sometimes I catch a different msg error about everything :/

I don't know if it's the cause but a few minute after that my box has been shutting alone by MAD and impossible to relaunch she. 

sorry for my English

[03-04 13:59:27.02] [       MainThread] [  MITMDataProcessor:41  ] [   ERROR] An error has been caught in function 'run', process 'MITMReceiver-1' ($
Traceback (most recent call last):                                                                                                                   
  File "start.py", line 216, in <module>                                                                                                             
    mitm_mapper, args, mapping_manager, db_wrapper)                                                                                                  
  File "/root/MAD/mapadroid/mitm_receiver/MITMReceiver.py", line 105, in __init__                                                                    
    data_processor.start()                                                                                                                           
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start                                                                           
    self._popen = self._Popen(self)                                                                                                                  
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen                                                                          
    return _default_context.get_context().Process._Popen(process_obj)                                                                                
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen                                                                          
    return Popen(process_obj)                                                                                                                        
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__                                                                      
    self._launch(process_obj)                                                                                                                        
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch                                                                       
    code = process_obj._bootstrap()                                                                                                                  
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                                      
    self.run()                                                                                                                                       
> File "/root/MAD/mapadroid/mitm_receiver/MITMDataProcessor.py", line 41, in run                                                                     
    self.process_data(item[0], item[1], item[2])                                                                                                     
  File "/root/MAD/mapadroid/mitm_receiver/MITMDataProcessor.py", line 91, in process_data                                                            
    self.__db_submit.mon_iv(origin, received_timestamp, data["payload"], self.__mitm_mapper)                                                         
  File "/root/MAD/mapadroid/db/DbPogoProtoSubmit.py", line 103, in mon_iv                                                                            
    spawnid = int(str(wild_pokemon["spawnpoint_id"]), 16)                                                                                            
ValueError: invalid literal for int() with base 16: ''

**Comment by ajmeese7** [comment]
Is it possible that you're passing a null value to `wild_pokemon["spawnpoint_id"]`? I just tried that in an online Python emulator and it threw the same error. Somehow I think your "spawnpoint_id" is an empty string in the array, or just not found in the array at all which is why `str` is returning an empty string to try to convert to an integer.

This should be easily implemented with null checking on the `str` conversion before it is passed to the `int` command with base 16, but I'm not familiar enough with Python to implement exception handling. I can look into it quickly to see if I can make a PR that handles your issue, but if not someone more experienced will have to throw it in.

**Comment by Mystic018** [comment]
Its possible for value null but I never touch or modifying something on db mad :/
