### ISSUE TITLE
PoGo 0.171.0 stuck on quest scanning

### ISSUE THREAD

**Issue by temp666** [Map-A-Droid/MAD#783]
Quest scanning with PoGo 0.171.0 will stuck on the new "Today" screen:
![grafik](https://user-images.githubusercontent.com/5256612/77690302-600c6980-6fa3-11ea-959c-f90e4e5063e4.png)

**Comment by cecpk** [comment]
grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr

**Comment by cecpk** [comment]
#784 
please test this PR - thx

**Comment by temp666** [comment]
i got this error:
[03-27 07:31:22.23] [clear_thread_x96mini115] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
> File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/MAD/mapadroid/worker/WorkerQuests.py", line 432, in _clear_thread
    self._clear_quests(self._delay_add)
  File "/home/pi/MAD/mapadroid/worker/MITMBase.py", line 202, in _clear_quests
    x, y = self._resocalc.get_quest_listview(self)[0], \
  File "/home/pi/MAD/mapadroid/utils/resolution.py", line 25, in get_quest_listview
    click_y = int(self._screen_y / 5.82)
TypeError: unsupported operand type(s) for /: 'str' and 'float'

**Comment by cecpk** [comment]
fixed with #784
