### ISSUE TITLE
Validate ptc_login field, server-side on connect, show error.

### ISSUE THREAD

**Issue by JabLuszko** [Map-A-Droid/MAD#790]
If you do not follow the ```username,password``` format and type something like ```username:password``` normal logs will show device trying to connect... and connect and connect.
https://i.imgur.com/7iqyzKr.png without any error [Discord claim].
If you start with -vv there is stacktrace.
```[03-30 03:57:11.95] [          scanner] [         screenPath:48  ] [    INFO] Set logintype: LoginType.ptc
[03-30 03:57:11.95] [          scanner] [         screenPath:522 ] [  DEBUG2] Fetching devicemappings of Test1
[03-30 03:57:11.95] [          scanner] [             server:191 ] [   ERROR] An error has been caught in function 'handler', process 'MainProcess' (11158), thread 'scanner' (139930126755584):
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f4431b2cbf8>
    └ <Thread(scanner, started 139930126755584)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x7f4414d752f0>
    └ <Thread(scanner, started 139930126755584)>

  File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(scanner, started 139930126755584)>,)
    └ <function Thread.run at 0x7f4431b2c9d8>

  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(scanner, started 139930126755584)>
    │    │        │    └ ()
    │    │        └ <Thread(scanner, started 139930126755584)>
    │    └ <bound method WebsocketServer.start_server of <mapadroid.websocket.WebsocketServer.WebsocketServer object at 0x7f4414cbf828>>
    └ <Thread(scanner, started 139930126755584)>

  File "/home/hidden/mad/mapadroid/websocket/WebsocketServer.py", line 96, in start_server
    self.__loop.run_forever()
    └ <mapadroid.websocket.WebsocketServer.WebsocketServer object at 0x7f4414cbf828>

  File "/usr/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f442e9a3378>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f442e984268>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f44143954f8>(<Future finished result=None>)>
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
    │    │          │    └ <member '_args' of 'Handle' objects>
    │    │          └ <Handle <TaskWakeupMethWrapper object at 0x7f44143954f8>(<Future finished result=None>)>
    │    └ <member '_callback' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f44143954f8>(<Future finished result=None>)>
> File "/home/hidden/.local/lib/python3.6/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
          │    │          │     └ '/'
          │    │          └ <websockets.server.WebSocketServerProtocol object at 0x7f4414327e10>
          │    └ <bound method WebsocketServer.__connection_handler of <mapadroid.websocket.WebsocketServer.WebsocketServer object at 0x7f4414...
          └ <websockets.server.WebSocketServerProtocol object at 0x7f4414327e10>

  File "/home/hidden/mad/mapadroid/websocket/WebsocketServer.py", line 187, in __connection_handler
    if not await self.__add_worker_and_thread_to_entry(entry, origin):
                 │                                     │      └ 'Test1'
                 │                                     └ <mapadroid.websocket.WebsocketConnectedClientEntry.WebsocketConnectedClientEntry object at 0x7f4414327cf8>
                 └ <mapadroid.websocket.WebsocketServer.WebsocketServer object at 0x7f4414cbf828>

  File "/home/hidden/mad/mapadroid/websocket/WebsocketServer.py", line 244, in __add_worker_and_thread_to_entry
    communicator=communicator)
                 └ <mapadroid.websocket.communicator.Communicator object at 0x7f44144104a8>

  File "/home/hidden/mad/mapadroid/worker/WorkerFactory.py", line 166, in get_worker_using_settings
    walker_configuration.walker_settings, walker_configuration.walker_area_name)
    │                    │                │                    └ <property object at 0x7f442df39728>
    │                    │                └ WalkerConfiguration(walker_settings={'walkervalue': '3', 'walkermax': '', 'walkertext': '', 'eventid': None, 'walkerarea': 6,...
    │                    └ <property object at 0x7f442df39458>
    └ WalkerConfiguration(walker_settings={'walkervalue': '3', 'walkermax': '', 'walkertext': '', 'eventid': None, 'walkerarea': 6,...

  File "/home/hidden/mad/mapadroid/worker/WorkerFactory.py", line 183, in get_worker
    pogo_window_manager=self.__pogo_windows, walker=walker_settings, event=self.__event)
                        │                           │                      └ <mapadroid.worker.WorkerFactory.WorkerFactory object at 0x7f4414cbfb38>
                        │                           └ {'walkervalue': '3', 'walkermax': '', 'walkertext': '', 'eventid': None, 'walkerarea': 6, 'walkertype': 'round'}
                        └ <mapadroid.worker.WorkerFactory.WorkerFactory object at 0x7f4414cbfb38>

  File "/home/hidden/mad/mapadroid/worker/WorkerMITM.py", line 28, in __init__
    mitm_mapper=mitm_mapper, pogoWindowManager=pogo_window_manager, walker=walker, event=event)
                │                              │                           │             └ <mapadroid.utils.event.Event object at 0x7f4414cc7c18>
                │                              │                           └ {'walkervalue': '3', 'walkermax': '', 'walkertext': '', 'eventid': None, 'walkerarea': 6, 'walkertype': 'round'}
                │                              └ <mapadroid.ocr.pogoWindows.PogoWindows object at 0x7f4414caf940>
                └ <AutoProxy[MitmMapper] object, typeid 'MitmMapper' at 0x7f4414cc7278>

  File "/home/hidden/mad/mapadroid/worker/MITMBase.py", line 37, in __init__
    pogoWindowManager=pogoWindowManager, walker=walker, event=event)
                      │                         │             └ <mapadroid.utils.event.Event object at 0x7f4414cc7c18>
                      │                         └ {'walkervalue': '3', 'walkermax': '', 'walkertext': '', 'eventid': None, 'walkerarea': 6, 'walkertype': 'round'}
                      └ <mapadroid.ocr.pogoWindows.PogoWindows object at 0x7f4414caf940>

  File "/home/hidden/mad/mapadroid/worker/WorkerBase.py", line 95, in __init__
    self._applicationArgs)
    │    └ Namespace(DEBUG=False, adb_server_ip='xxxxxxx', adb_server_port=xxx, advanced_config=True, auto_hatch=False, auto_hatch_nu...
    └ <mapadroid.worker.WorkerMITM.WorkerMITM object at 0x7f44143f6668>

  File "/home/hidden/mad/mapadroid/ocr/screenPath.py", line 44, in __init__
    self.get_login_accounts()
    │    └ <function WordToScreenMatching.get_login_accounts at 0x7f442df93730>
    └ <mapadroid.ocr.screenPath.WordToScreenMatching object at 0x7f44143f6748>

  File "/home/hidden/mad/mapadroid/ocr/screenPath.py", line 62, in get_login_accounts
    password = ptc_temp[1]
               └ ['login:password']

IndexError: list index out of range
```

Seen it twice on discord last week :P

**Comment by Expl0dingBanana** [comment]
This was fixed in d79e2fd.  Please reopen if you see this problem again.
