### ISSUE TITLE
Mad stuck at -v mode

### ISSUE THREAD

**Issue by cyphercris** [Map-A-Droid/MAD#792]
i have problem when run mad with -v its stuck and not go
[03-31 00:11:33.51] [         Thread-2] [     MappingManager:625 ] [    INFO] Mappings have been updated
[03-31 00:11:33.51] [devicesettings_setter_consumer] [     MappingManager:119 ] [    INFO] Starting Devicesettings consumer Thread
[03-31 00:11:33.51] [    event_checker] [          DbWrapper:1112] [   DEBUG] DbWrapper::get_current_event called
[03-31 00:11:33.52] [    event_checker] [          DbWrapper:1123] [    INFO] There is no active event - returning default value (1) (Lure Duration: 30)
[03-31 00:11:33.70] [     route_joiner] [     MappingManager:69  ] [    INFO] Try to join routethreads for route Klonownica
[03-31 00:12:33.58] [    event_checker] [          DbWrapper:1112] [   DEBUG] DbWrapper::get_current_event called
[03-31 00:12:33.58] [    event_checker] [          DbWrapper:1123] [    INFO] There is no active event - returning default value (1) (Lure Duration: 30)

On -v mode last two lines is repeated and nothing working.

**Comment by sn0opy** [comment]
Is this still a problem? I was not able to reproduce this with 2 different instances

**Comment by cyphercris** [comment]
```
[04-09 19:35:04.37] [devicesettings_setter_consumer] [     MappingManager:119 ] [    INFO] Starting Devicesettings consumer Thread
[04-09 19:35:04.38] [    event_checker] [          DbWrapper:1123] [   DEBUG] DbWrapper::get_current_event called
[04-09 19:35:04.39] [MainProcess|event_checker] [PooledQueryExecutor:92  ] [  DEBUG4] select `id`, `event_lure_duration` from trs_event where now() between `event_start` and `event_end` and `event_name`<>'DEFAULT'
[04-09 19:35:04.39] [    event_checker] [          DbWrapper:1134] [    INFO] There is no active event - returning default value (1) (Lure Duration: 30)
[04-09 19:36:04.45] [    event_checker] [          DbWrapper:1123] [   DEBUG] DbWrapper::get_current_event called
[04-09 19:36:04.45] [MainProcess|event_checker] [PooledQueryExecutor:92  ] [  DEBUG4] select `id`, `event_lure_duration` from trs_event where now() between `event_start` and `event_end` and `event_name`<>'DEFAULT'
[04-09 19:36:04.45] [    event_checker] [          DbWrapper:1134] [    INFO] There is no active event - returning default value (1) (Lure Duration: 30)
```
Still stuck on this.

Maybe something wrong with event future on my db. When try delete all unfenced spawnpoints get this and nothing happen.
![IMG_20200409_194138](https://user-images.githubusercontent.com/16975350/78924559-5c480f00-7a9a-11ea-891f-ea87ca093dd0.jpg)

**Comment by sn0opy** [comment]
Does this also happen if you run MAD in non-debug mode without `-v`. Does MAD work in general if you have debug mode enabled?

**Comment by cyphercris** [comment]
Just if I run mad with -v (vvv). 
With -v stuck in this place and output is repeated, nothting scan / madmin not work.

**Comment by ChaosEmpire** [comment]
I dont know if this will help
But i have had a curiosity when my device json files have been broken
without -v Igot a crash message and mad stopped

with -v i got a different behaviour, mad started and repeated the event handler messages (and stuck at this point)

maybe it helps to find the area, of the error described above

**Comment by Expl0dingBanana** [comment]
I am able to reproduce this on my development system (not going to touch the production one).  When I send the interrupt signal I always see a traceback with MitmMapper:

Traceback (most recent call last):
  File "start.py", line 217, in <module>
    mitm_mapper: MitmMapper = mitm_mapper_manager.MitmMapper(mapping_manager, db_wrapper.stats_submit)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 724, in temp
    token, exp = self._create(typeid, *args, **kwds)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 609, in _create
    id, exposed = dispatch(conn, None, 'create', (typeid,)+args, kwds)
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 79, in dispatch
    kind, result = c.recv()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)

**Comment by Expl0dingBanana** [comment]
This has something to do with PlayerStats.py (or just a coincidence but it has always stopped there for me) but I cannot figure out why as the logging is standard in there.  If I modify that file to use the module `logging` vs `loguru` I no longer run into this issue.

**Comment by sn0opy** [comment]
Still not 100% where and why this happens. I am not able to reproduce this with every start. Sometimes it occurs and sometimes doesn't. Please update MAD to latest master and start it with `-v -nec` and see, if the problem still occurs. 

The `-nec` option will disable the event checker. So if you have any events configured, they will be ignored!

**Comment by cyphercris** [comment]
With -nec works, thanks.

**Comment by sn0opy** [comment]
Keep in mind, this is just for debugging purposes. You basically kill the event feature by using `-nec`.

**Comment by Expl0dingBanana** [comment]
Please try with the latest master and let me know if the issue has been resolved.

**Comment by cyphercris** [comment]
Logging works without -nec. Thank you.
