### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by kamieniarz** [Map-A-Droid/MAD#813]
This error is a rare thing but it's very annoying cause it shows up at night few minutes after quest scan launch. It starts from this for some devices:

```[04-20 01:34:05.04] [           device21] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
> File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/(...)/MAD/mapadroid/worker/WorkerBase.py", line 420, in _main_work_thread
    time_snapshot, process_location = self._move_to_location()
  File "/(...)/MAD/mapadroid/worker/WorkerQuests.py", line 350, in _move_to_location
    if not self._mapping_manager.routemanager_present(self._routemanager_name) \
  File "<string>", line 2, in routemanager_present
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 796, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```

Right after that (like in ms) it changes to this on other devices:

```[04-20 01:34:05.09] [           device25] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
> File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/(...)/MAD/mapadroid/worker/WorkerBase.py", line 382, in _main_work_thread
    settings = self._internal_grab_next_location()
  File "/(...)/MAD/mapadroid/worker/WorkerBase.py", line 561, in _internal_grab_next_location
    self._origin)
  File "<string>", line 2, in routemanager_get_next_location
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 796, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

And ends up with broken pipe error, which basically kills the whole MAD untill I restart it:

```[04-20 01:34:09.09] [          scanner] [             server:191 ] [   ERROR] An error has been caught in function 'handler', process 'MainProcess' (30803), thread 'scanner' (139776657176320):
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/(...)/MAD/mapadroid/websocket/WebsocketServer.py", line 96, in start_server
    self.__loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
> File "/(...)/.local/lib/python3.7/site-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "/(...)/MAD/mapadroid/websocket/WebsocketServer.py", line 160, in __connection_handler
    origin: Optional[str] = await self.__authenticate_connection(websocket_client_connection)
  File "/(...)/MAD/mapadroid/websocket/WebsocketServer.py", line 279, in __authenticate_connection
    if self.__mapping_manager is None or origin not in self.__mapping_manager.get_all_devicemappings().keys():
  File "<string>", line 2, in get_all_devicemappings
  File "/usr/lib/python3.7/multiprocessing/managers.py", line 795, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

It's not the first time I had this error and it's trully annoying cause my quests should be scanned during the night but when I wake up 7h later I have like 5% of all quests scanned cause mad died...

**Comment by kamieniarz** [comment]
I moved to a new VPS with a db backup from the old one and I had that error again... That's so annoying. How many vvvvv do you need to find the issue? Cause I guess it will happen again and again

**Comment by kamieniarz** [comment]
Another day, another crash... I started mad with - vvvv so tomorrow (cause I guess it'll happen again) I'll post more detailed logs

**Comment by kamieniarz** [comment]
I deleted my previous database and recreated everything from zero to make sure it's not a db issue. I had no issue during last 2 days but last night issue appeared again...

```[05-02 01:33:50.64] [           X96m10] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
> File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/(...)/mad/mapadroid/worker/WorkerBase.py", line 451, in _main_work_thread
    self._internal_cleanup()
  File "/(...)/mad/mapadroid/worker/WorkerBase.py", line 322, in _internal_cleanup
    self._mapping_manager.unregister_worker_from_routemanager(self._routemanager_name, self._origin)
  File "<string>", line 2, in unregister_worker_from_routemanager
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 757, in _callmethod
    kind, result = conn.recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

Is anyone able to help me? Any ideas how to fix it?

**Comment by kamieniarz** [comment]
Few days without any issue but this night it happened again and it was again after 1:20am but this time it started with a different error than earlier and also logs gone crazy cause they're not in order:

```[05-07 01:23:09.25] [clear_thread_device18] [       WorkerQuests:523 ] [   ERROR] Did not get any text in inventory
[05-07 01:23:09.30] [clear_thread_device18] [       WorkerQuests:527 ] [    INFO] Found item None
[05-07 01:23:09.42] [         phoneS5] [         WorkerBase:449 ] [    INFO] Worker phoneS5 finished iteration, continuing work
[05-07 01:23:09.41] [           device39] [       WorkerQuests:391 ] [    INFO] Processing Stop / Quest...
[05-07 01:23:09.79] [       MainThread] [  MITMDataProcessor:79  ] [ SUCCESS] GMO przetworzone - device35
[05-07 01:23:09.84] [       MainThread] [  MITMDataProcessor:79  ] [ SUCCESS] GMO przetworzone - device39
[05-07 01:23:10.00] [       MainThread] [  MITMDataProcessor:79  ] [ SUCCESS] GMO przetworzone - device17
[05-07 01:23:10.01] [       MainThread] [  MITMDataProcessor:79  ] [ SUCCESS] GMO przetworzone - device26
[05-07 01:23:09.95] [MainProcess|device18] [   RouteManagerBase:575 ] [    INFO] Worker device18 getting a nearby prio event Location(lat=52.40789, lng=16.889457)
[05-07 01:23:10.03] [MainProcess|phoneS5] [   RouteManagerBase:733 ] [    INFO] gorzow: Moving on with location Location(lat=52.76171856437218, lng=15.241607289542491) [21 coords left (Workerpool)]
[05-07 01:23:09.30] [clear_thread_device18] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
> File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/mad/mapadroid/worker/WorkerQuests.py", line 428, in _clear_thread
    self.clear_box(self._delay_add)
  File "/home/user/mad/mapadroid/worker/WorkerQuests.py", line 530, in clear_box
    if self.similar(text, item_text) > 0.6:
  File "/home/user/mad/mapadroid/worker/WorkerQuests.py", line 52, in similar
    return SequenceMatcher(None, a, b).ratio()
  File "/usr/lib/python3.6/difflib.py", line 644, in ratio
    matches = sum(triple[-1] for triple in self.get_matching_blocks())
  File "/usr/lib/python3.6/difflib.py", line 467, in get_matching_blocks
    la, lb = len(self.a), len(self.b)
TypeError: object of type 'NoneType' has no len()
[05-07 01:23:10.29] [           device33] [           MITMBase:176 ] [ SUCCESS] Got the data requested
[05-07 01:23:10.45] [           device15] [       WorkerQuests:397 ] [    INFO] Open Stop
[05-07 01:23:10.56] [           device18] [       WorkerQuests:308 ] [    INFO] Timediff between now and last action time: 39
[05-07 01:23:10.58] [           device18] [       WorkerQuests:327 ] [    INFO] No need to wait before spinning, continuing...
[05-07 01:23:10.60] [           device18] [       WorkerQuests:391 ] [    INFO] Processing Stop / Quest...
[05-07 01:23:10.73] [           device33] [       WorkerQuests:750 ] [    INFO] Spin Stop
```

**Comment by kamieniarz** [comment]
Another day another error. Would be nice if someone could even TRY to fix it :)

```[05-22 02:30:04.10] [       MainThread] [  MITMDataProcessor:71  ] [    INFO] Processing GMO received from device38. Received at 2020-05-22 02:30:02
[05-22 02:30:04.22] [           device12] [           MITMBase:191 ] [ WARNING] Timeout waiting for data
[05-22 02:30:04.51] [       MainThread] [  MITMDataProcessor:71  ] [    INFO] Processing GMO received from device15. Received at 2020-05-22 02:30:02
[05-22 02:30:04.23] [clear_thread_device44] [           MITMBase:320 ] [    INFO] Delete old quest 3
[05-22 02:30:12.69] [worker_join_thread] [    WebsocketServer:139 ] [    INFO] Trying to join worker thread
[05-22 02:30:14.64] [           system] [              start:123 ] [    INFO] Instance Name: "mad" - Memory usage: 0.43042755126953125 - CPU usage: 38.4
[05-22 02:30:25.03] [worker_join_thread] [    WebsocketServer:139 ] [    INFO] Trying to join worker thread
[05-22 02:30:29.72] [          scanner] [WebsocketConnectedClientEntry:94  ] [ WARNING] Timeout, increasing timeout-counter of device43
[05-22 02:30:37.75] [worker_join_thread] [    WebsocketServer:139 ] [    INFO] Trying to join worker thread
[05-22 02:30:39.68] [       MainThread] [  MITMDataProcessor:41  ] [   ERROR] An error has been caught in function 'run', process 'MITMReceiver-12' (14134), thread 'MainThread' (139935425840960):
Traceback (most recent call last):
  File "start.py", line 226, in <module>
    enable_configmode=args.config_mode)
  File "/(...)/mad/mapadroid/mitm_receiver/MITMReceiver.py", line 154, in __init__
    data_processor.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 73, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
> File "/(...)/mad/mapadroid/mitm_receiver/MITMDataProcessor.py", line 41, in run
    self.process_data(item[0], item[1], item[2])
  File "/(...)/mad/mapadroid/mitm_receiver/MITMDataProcessor.py", line 81, in process_data
    mon_ids_iv = self.__mitm_mapper.get_mon_ids_iv(origin)
  File "<string>", line 2, in get_mon_ids_iv
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
ConnectionResetError: [Errno 104] Connection reset by peer
```
After this one there was well known EOFError and broken pipe.

**Comment by sn0opy** [comment]
Since you reported issues with #864 as well. Are you 100% sure that you're devices, your network or your server isn't broken in some way? You're the only one constantly reporting this issue.

"Connection reset by peer" usually means, that MAD tried to reply to a packet, that the intial sender doesn't know any more which is usually the case when the connection has been killed on your device's end. Please check your setup. In doubt create a clean install with a clean DB and move a few devices over to it. There's not much we can do here, since this is a general error obvously occuring in several places.

2nd theory: there is an issue on your system while running multiprocessing/multithreading apps. Again, since you're the only on having this issue right now, I assume it's something broken on your server. Try to create a clean MAD setup while using Python's virtualenv to make sure no othe (broken) dependencies cause this issue.

**Comment by kamieniarz** [comment]
That's my second VPS (from a different provider) I'm having issues with - so moving to another one or even starting with clean install and clean db didn't help. It ALWAYS happens when doing quests 

But basically you're telling me it can be device related but it can't be fixed tho? The way you explained "Connection reset by peer" seems to me like this issue could happen to anyone. I don't know if it's internet connection issues or one of my devices dies or sth - there is no such thing in logs that would point that out. And alos as I said - it happens only during quest scans. MAD generally works for 18h with no issues but then it dies when doing quests during the night.

So if it's an issue with connection between device and MAD - could you fix it maybe?

**Comment by sn0opy** [comment]
The only thing I've found is a similar issue with another python related tool: https://github.com/pytorch/pytorch/issues/9127

As this is the only thing that comes close to your issue, my 1st theory was that it could somehow be related to multiprocessing on MAD's end. But

1. the logs from above don't really help to pinpoint the actual issue
2. there's nobody else reporting the same issue

As there aren't any other network related things but the connection between a device and MAD, the device or something inbetween could for whatever reason kill the connection causing the exact same error.

We would like to fix it, but we don't know when and why this issue occurs so don't know how to fix it.

**Comment by kamieniarz** [comment]
So can't MAD just prevent such actions? If it's rly a connection issue that's just ridiculous that it entirely kills MAD, especially if it's 1 (?) device or whatever and during the night when quest scanning. 

As I said before - this issue never happened to me during the day or during anything else than quests but it happened like 15 times already every time during quests scan... 

If you need more logs I can do -vvvvv or whatever, just tell me how many v would it need if so

**Comment by sn0opy** [comment]
No it's not just something we could prevent. If we could "just" prevent it, we would do so.

At night time, people usually scan for quests causing a lot more things to happen which then causes way more data to be sent in and out etc.

Right now, we don't know why this occurs and further logs wouldn't help either. There's no fix for this right now.

**Comment by Expl0dingBanana** [comment]
I believe this is related to the networking issues you have been encountering.  Please re-open the issue if you believe its not related

**Comment by motifMachine** [comment]
> I believe this is related to the networking issues you have been encountering. Please re-open the issue if you believe its not related

There is no networking involved in my setup. I still run into this issue randomly. Appears reducing num_workers from the original 32 to 30 seems helps.
