### ISSUE TITLE
An unhanded exception in RouteManagerBase _check_routepools

### ISSUE THREAD

**Issue by KyleYu** [Map-A-Droid/MAD#824]
I meet an issue.
A sample log is as follows
```
[04-22 13:30:23.66] [_check_routepools_7m] [   RouteManagerBase:835 ] [ WARNING] Worker 7m has not accessed a location in 300 seconds, removing from routemanager
[04-22 13:30:23.66] [_check_routepools_7m] [   RouteManagerBase:213 ] [    INFO] Worker 7m unregistering from routemanager 7m
[04-22 13:30:23.66] [_check_routepools_7m] [   RouteManagerBase:216 ] [    INFO] Deleting old routepool of 7m
[04-22 13:30:23.66] [_check_routepools_7m] [   RouteManagerBase:230 ] [    INFO] Routemanager 7m does not have any subscribing workers anymore, calling stop
[04-22 13:30:23.66] [_check_routepools_7m] [   RouteManagerBase:170 ] [    INFO] Adding route 7m to queue
[04-22 13:30:23.66] [_check_routepools_7m] [    RouteManagerMon:71  ] [    INFO] Shutdown Route 7m
[04-22 13:30:23.66] [_check_routepools_7m] [   RouteManagerBase:176 ] [    INFO] Shutdown of route 7m completed
[04-22 13:30:23.66] [_check_routepools_7m] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f01739dbc20>
    └ <Thread(_check_routepools_7m, started daemon 139640887355136)>
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x7f015b169dd0>
    └ <Thread(_check_routepools_7m, started daemon 139640887355136)>
pokemon_mad  |
> File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(_check_routepools_7m, started daemon 139640887355136)>,)
    └ <function Thread.run at 0x7f01739db9e0>
pokemon_mad  |
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │             │             └ <Thread(_check_routepools_7m, started daemon 139640887355136)>
    │             └ <Thread(_check_routepools_7m, started daemon 139640887355136)>
    └ <Thread(_check_routepools_7m, started daemon 139640887355136)>
pokemon_mad  |
  File "/usr/src/app/mapadroid/route/RouteManagerBase.py", line 837, in _check_routepools
    raise InternalStopWorkerException
          └ <class 'mapadroid.utils.madGlobals.InternalStopWorkerException'>
pokemon_mad  |
mapadroid.utils.madGlobals.InternalStopWorkerException
[04-22 13:30:23.66] [_check_routepools_7m] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
> File "start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/src/app/mapadroid/route/RouteManagerBase.py", line 837, in _check_routepools
    raise InternalStopWorkerException
mapadroid.utils.madGlobals.InternalStopWorkerException
```
There is an exception, InternalStopWorkerException, introduced in https://github.com/Map-A-Droid/MAD/commit/7ea245ad9953d0498ab0198ab09aec401bd6d9c1.
The exception is unhanded by the related route classes.
After this happens, workers would not work again.

**Comment by Grennith** [comment]
Hi,
could you run the minor_routemanager_fixes branch please and report any further issues that may exist? :)
