### ISSUE TITLE
Unhandled exception after recalc route

### ISSUE THREAD

**Issue by crazy1frank** [Map-A-Droid/MAD#836]
If I recalc a route which is currently used by a device, I get an unhandled exception as soon as the recalc is finished and MAD tries to shut down the old route. Recalc a route/area which is currently not in use works flawless.
I made a fresh pull before I discovered this fault.
```[04-29 09:33:49.30] [      Thread-3523] [calculate_route_optimized:70  ] [    INFO] Route calculation is 88.0% complete for VH Butterfield (gold/mon)
[04-29 09:33:49.38] [      Thread-3523] [calculate_route_optimized:70  ] [    INFO] Route calculation is 90.0% complete for VH Butterfield (gold/mon)
[04-29 09:33:49.41] [      Thread-3523] [calculate_route_optimized:70  ] [    INFO] Route calculation is 95.0% complete for VH Butterfield (gold/mon)
[04-29 09:33:49.50] [      Thread-3523] [          routecalc:168 ] [    INFO] Calculated route in 0.03602568972079704 minutes
[04-29 09:33:49.51] [      Thread-3523] [   RouteManagerBase:206 ] [    INFO] Worker ATV011 unregistering from routemanager VH Butterfield (gold/mon)
[04-29 09:33:49.51] [      Thread-3523] [   RouteManagerBase:209 ] [    INFO] Deleting old routepool of ATV011
[04-29 09:33:49.51] [      Thread-3523] [   RouteManagerBase:223 ] [    INFO] Routemanager VH Butterfield (gold/mon) does not have any subscribing workers anymore, calling stop
[04-29 09:33:49.51] [      Thread-3523] [   RouteManagerBase:168 ] [    INFO] Adding route VH Butterfield (gold/mon) to queue
[04-29 09:33:49.51] [      Thread-3523] [    RouteManagerMon:71  ] [    INFO] Shutdown Route VH Butterfield (gold/mon)
[04-29 09:33:49.51] [      Thread-3523] [   RouteManagerBase:174 ] [    INFO] Shutdown of route VH Butterfield (gold/mon) completed
[04-29 09:33:49.51] [      Thread-3523] [              start:63  ] [CRITICAL] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
> File "/home/crazyfrank/MAD/start.py", line 57, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/crazyfrank/MAD/mapadroid/route/RouteManagerBase.py", line 355, in recalc_route_adhoc
    for worker in self._workers_registered:
RuntimeError: Set changed size during iteration
[04-29 09:33:49.68] [     route_joiner] [     MappingManager:69  ] [    INFO] Try to join routethreads for route VH Butterfield (gold/mon)
[04-29 09:33:49.70] [           ATV010] [         WorkerBase:449 ] [    INFO] Worker ATV010 finished iteration, continuing work
```
I can see the new calculated route in the database but my worker is still running the old route.

**Comment by Expl0dingBanana** [comment]
It appears this was fixed in 796066e.  Please re-open the ticket if you see the issue occur again.
