### ISSUE TITLE
Semicolon inside job SYNTAX does not work.

### ISSUE THREAD

**Issue by JabLuszko** [Map-A-Droid/MAD#848]
Example job:
```
{
            "Test semicolon!":
        [
                {
                        "TYPE": "jobType.PASSTHROUGH",
                        "SYNTAX": "echo TEST; echo OK"
                }
        ]
}
```

Trying to escape semicolon with one backlash renders json invalid. Escaping with two backslashes bring back KO: invalid input.
Any other ideas?

[05-11 21:28:17.82] [          scanner] [    WebsocketServer:231 ] [   ERROR] Other unhandled exception during registration of xxx: invalid literal for int() with base 10: 'KO: invalid input'
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "start.py", line 60, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mad/MAD/mapadroid/websocket/WebsocketServer.py", line 96, in start_server
    self.__loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 534, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1771, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
> File "/home/mad/MAD/mapadroid/websocket/WebsocketServer.py", line 228, in __connection_handler
    await receiver_task
  File "/home/mad/MAD/mapadroid/websocket/WebsocketServer.py", line 318, in __client_message_receiver
    await self.__on_message(client_entry, message)
  File "/home/mad/MAD/mapadroid/websocket/WebsocketServer.py", line 328, in __on_message
    message_id = int(splitup[0])
ValueError: invalid literal for int() with base 10: 'KO: invalid input'
```

**Comment by JabLuszko** [comment]
Update RGC to at least v1.10.1.
