### ISSUE TITLE
MAD 1st started instance Internal server error

### ISSUE THREAD

**Issue by dkmur** [Map-A-Droid/MAD#902]
The first started instance will give 
``Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`` 
whenever I try to access i.e.
- area settings
- walkers
Or load new IV list via API.

some other options like changing a geofence are possible.

MAD log shows:
```
[06-14 22:56:28.21] [          Unknown] [                app:1936] [E] An error has been caught in function 'dispatch_request', process 'MainProcess' (2595), thread 'Thread-604' (140396717639424):
    return AREA_MAPPINGS[mode](data_manager, identifier=identifier)
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
```

**Comment by sn0opy** [comment]
Try to run MAD with `-v` and see if you get any further logs because this doesn't really help to find the actual issue.

You can try to print `mode` and `identifier` right before this line.

https://github.com/Map-A-Droid/MAD/blob/master/mapadroid/data_manager/modules/__init__.py#L23

**Comment by dkmur** [comment]
-v provides no addition info from what I can tell
```
grep -w '[E]\|[C]'
[06-14 23:31:14.21] [          Unknown] [                app:1936] [E] An error has been caught in function 'dispatch_request', process 'MainProcess' (9895), thread 'Thread-12' (140153917638400):
[06-14 23:31:14.38] [           madmin] [             madmin:37  ] [C] An unhanded exception occurred!
```

as for the insert a print, a bit more detail.....the actual line really that needs to be put in....would be required for this idiot. Tried but ofcourse MAD would not start anymore since I know shit about this stuff

**Comment by JabLuszko** [comment]
Something like that https://raw.githubusercontent.com/JabLuszko/MAD/patch-115/mapadroid/data_manager/modules/__init__.py just replace file.

Also please stop greping logs like that, there could be much more things before and earlier. At least add `-C 15` that will show 15 lines before and after.

**Comment by dkmur** [comment]
more detail with these changes, have the log, to whom do I send it?

**Comment by spammer23** [comment]
same issue as https://github.com/Map-A-Droid/MAD/issues/733

**Comment by Expl0dingBanana** [comment]
@dkmur can you run the following SQL command and provide the output?

```SQL
SELECT sa.`area_id`, sub_area.`routecalc_id`, sa.`instance_id` AS 'Area Instance', sub_area.`instance_id` AS 'Route Instance'
FROM `settings_area` sa
INNER JOIN (
    SELECT rc.`routecalc_id`, rc.`instance_id`, IFNULL(iv.`area_id`, IFNULL(mon.`area_id`, IFNULL(ps.`area_id`, IFNULL(ra.`area_id`, -1)))) AS `area_id`
    FROM `settings_routecalc` rc
    LEFT JOIN `settings_area_iv_mitm` iv ON iv.`routecalc` = rc.`routecalc_id`
    LEFT JOIN `settings_area_mon_mitm` mon ON mon.`routecalc` = rc.`routecalc_id`
    LEFT JOIN `settings_area_pokestops` ps ON ps.`routecalc` = rc.`routecalc_id`
    LEFT JOIN `settings_area_raids_mitm` ra ON ra.`routecalc` = rc.`routecalc_id`
) sub_area ON sub_area.`area_id` = sa.`area_id`
```

**Comment by Expl0dingBanana** [comment]
@spammer23 can you also run the same query?

**Comment by spammer23** [comment]
+---------+--------------+---------------+----------------+
| area_id | routecalc_id | Area Instance | Route Instance |
+---------+--------------+---------------+----------------+
|       1 |            1 |             1 |              1 |
|      13 |            4 |             1 |              1 |
|      14 |            5 |             1 |              1 |
|      15 |            6 |             1 |              1 |
|      16 |            7 |             1 |              1 |
|       2 |            8 |             1 |              1 |
|       3 |            9 |             1 |              1 |
|       5 |           11 |             1 |              1 |
|       6 |           12 |             1 |              1 |
|       7 |           13 |             1 |              1 |
|       8 |           14 |             1 |              1 |
|      19 |           15 |             1 |              1 |
|      22 |           18 |             1 |              1 |
|      23 |           19 |             1 |              1 |
|      24 |           20 |             1 |              1 |
|      25 |           21 |             1 |              1 |
|      27 |           23 |             1 |              1 |
|      28 |           24 |             1 |              1 |
|      29 |           25 |             1 |              1 |
+---------+--------------+---------------+----------------+
19 rows in set (0.007 sec)

**Comment by dkmur** [comment]
![Screenshot_20200615-140350_Termius](https://user-images.githubusercontent.com/42545952/84655415-35321180-af11-11ea-8bf6-e87c9e97f1b3.jpg)

**Comment by Expl0dingBanana** [comment]
That query will need to be revised a bit since itll only return one row per routecalc.  Was everything done through MADmin or did yall link a routecalc to the area using SQL?

**Comment by dkmur** [comment]
All madmin for me

**Comment by spammer23** [comment]
All madmin for me, too
(No areas in second instance, no devices connected - just for webhooks)

**Comment by Expl0dingBanana** [comment]
Steps to reproduce:
Spin up instance 1
Spin up instance 2
Load area from instance one and get traceback

**Comment by spammer23** [comment]
```
`Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1c3a54cbf8>
    └ <Thread(Thread-68, started daemon 139756415477504)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x7f1c1ca4a510>
    └ <Thread(Thread-68, started daemon 139756415477504)>

  File "start.py", line 58, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(Thread-68, started daemon 139756415477504)>,)
    └ <function Thread.run at 0x7f1c3a54c9d8>

  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-68, started daemon 139756415477504)>
    │    │        │    └ (<socket.socket fd=103, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 4000), raddr=...
    │    │        └ <Thread(Thread-68, started daemon 139756415477504)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>>
    └ <Thread(Thread-68, started daemon 139756415477504)>
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 44842)
    │    │              └ <socket.socket fd=103, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 4000), raddr=(...
    │    └ <function BaseServer.finish_request at 0x7f1c295f7840>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>
    │    │                   │        └ ('127.0.0.1', 44842)
    │    │                   └ <socket.socket fd=103, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 4000), raddr=(...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1c29594e18>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
    │                      │      └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>
    │                      └ <function BaseHTTPRequestHandler.handle at 0x7f1c2960ca60>
    └ <class 'http.server.BaseHTTPRequestHandler'>

  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1c29516048>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
           │    └ <function WSGIRequestHandler.run_wsgi at 0x7f1c29594d90>
           └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <Flask 'mapadroid.madmin.madmin'>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x7f1bec7671e0>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
                       │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f1bec767268>
                       │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=103>, 'wsgi.errors': <_io.TextIOWr...
                       └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f1bec767268>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=103>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <mapadroid.madmin.reverseproxy.ReverseProxied object at 0x7f1c1c08ffd0>
           └ <Flask 'mapadroid.madmin.madmin'>

  File "/opt/MAD/mapadroid/madmin/reverseproxy.py", line 26, in __call__
    return self.app(environ, start_response)
           │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f1bec767268>
           │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=103>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <werkzeug.middleware.proxy_fix.ProxyFix object at 0x7f1c1ca2d5f8>
           └ <mapadroid.madmin.reverseproxy.ReverseProxied object at 0x7f1c1c08ffd0>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
           │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f1bec767268>
           │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=103>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <bound method Flask.wsgi_app of <Flask 'mapadroid.madmin.madmin'>>
           └ <werkzeug.middleware.proxy_fix.ProxyFix object at 0x7f1c1ca2d5f8>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x7f1c291b5b70>
               └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
         │    └ <function Flask.dispatch_request at 0x7f1c291b5ae8>
         └ <Flask 'mapadroid.madmin.madmin'>

> File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
           │    │              │    │           │   └ {}
           │    │              │    │           └ <Request 'xxx/settings/areas' [GET]>
           │    │              │    └ 'settings_areas'
           │    │              └ <Rule '/settings/areas' (GET, POST, HEAD, OPTIONS) -> settings_areas>
           │    └ {'static': <bound method _PackageBoundObject.send_static_file of <Flask 'mapadroid.madmin.madmin'>>, 'statistics': <bound met...
           └ <Flask 'mapadroid.madmin.madmin'>

  File "/opt/MAD/mapadroid/madmin/functions.py", line 25, in decorated
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<mapadroid.madmin.routes.config.config object at 0x7f1c1c073f98>,)
           └ <function config.settings_areas at 0x7f1c1ca632f0>

  File "/opt/MAD/mapadroid/madmin/routes/config.py", line 228, in settings_areas
    return self.process_element(**required_data)
           │    │                 └ {'identifier': 'id', 'base_uri': 'api_area', 'data_source': 'area', 'redirect': 'settings_areas', 'html_single': 'settings_si...
           │    └ <function config.process_element at 0x7f1c1ca5dd90>
           └ <mapadroid.madmin.routes.config.config object at 0x7f1c1c073f98>

  File "/opt/MAD/mapadroid/madmin/routes/config.py", line 158, in process_element
    included_data[section] = self._data_manager.get_root_resource(data_source)
    │             │          │    │             │                 └ 'area'
    │             │          │    │             └ <function DataManager.get_root_resource at 0x7f1c299dcae8>
    │             │          │    └ <mapadroid.data_manager.DataManager object at 0x7f1c1c1d5eb8>
    │             │          └ <mapadroid.madmin.routes.config.config object at 0x7f1c1c073f98>
    │             └ 'area'
    └ {'advcfg': True, 'base_uri': '/api/area', 'identifier': None, 'monlist': OrderedDict([(1, <mapadroid.data_manager.modules.mon...

  File "/opt/MAD/mapadroid/data_manager/__init__.py", line 80, in get_root_resource
    elem = resource_class(self, identifier=identifier)
           │              │                └ 28
           │              └ <mapadroid.data_manager.DataManager object at 0x7f1c1c1d5eb8>
           └ <function AreaFactory at 0x7f1c29a1f400>

  File "/opt/MAD/mapadroid/data_manager/modules/__init__.py", line 23, in AreaFactory
    return AREA_MAPPINGS[mode](data_manager, identifier=identifier)
           │             │     │                        └ 28
           │             │     └ <mapadroid.data_manager.DataManager object at 0x7f1c1c1d5eb8>
           │             └ 'mon_mitm'
           └ {'idle': <class 'mapadroid.data_manager.modules.area_idle.AreaIdle'>, 'iv_mitm': <class 'mapadroid.data_manager.modules.area_...

  File "/opt/MAD/mapadroid/data_manager/modules/resource.py", line 186, in __init__
    self._load()
    │    └ <function Area._load at 0x7f1c29a3a1e0>
    └ <mapadroid.data_manager.modules.area_mon_mitm.AreaMonMITM object at 0x7f1c14515588>

  File "/opt/MAD/mapadroid/data_manager/modules/area.py", line 41, in _load
    routecalc = self._data_manager.get_resource('routecalc', self._data['fields']['routecalc'])
                │                                            └ <mapadroid.data_manager.modules.area_mon_mitm.AreaMonMITM object at 0x7f1c14515588>
                └ <mapadroid.data_manager.modules.area_mon_mitm.AreaMonMITM object at 0x7f1c14515588>

  File "/opt/MAD/mapadroid/data_manager/__init__.py", line 38, in get_resource
    return modules.MAPPINGS[section](self, identifier=identifier)
           │       │        │        │                └ 24
           │       │        │        └ <mapadroid.data_manager.DataManager object at 0x7f1c1c1d5eb8>
           │       │        └ 'routecalc'
           │       └ {'area': <function AreaFactory at 0x7f1c29a1f400>, 'area_nomode': <class 'mapadroid.data_manager.modules.area.Area'>, 'auth':...
           └ <module 'mapadroid.data_manager.modules' from '/opt/MAD/mapadroid/data_manager/modules/__init__.py'>

  File "/opt/MAD/mapadroid/data_manager/modules/resource.py", line 186, in __init__
    self._load()
    │    └ <function RouteCalc._load at 0x7f1c29a55d90>
    └ <mapadroid.data_manager.modules.routecalc.RouteCalc object at 0x7f1c145015f8>

  File "/opt/MAD/mapadroid/data_manager/modules/routecalc.py", line 57, in _load
    raise UnknownIdentifier()
          └ <class 'mapadroid.data_manager.dm_exceptions.UnknownIdentifier'>

mapadroid.data_manager.dm_exceptions.UnknownIdentifier
[06-15 14:57:09.70] [          Unknown] [E] An error has been caught in function 'dispatch_request', process 'MainProcess' (22764), thread 'Thread-68' (139756415477504):
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "start.py", line 58, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/MAD/mapadroid/madmin/reverseproxy.py", line 26, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
> File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/MAD/mapadroid/madmin/functions.py", line 25, in decorated
    return func(*args, **kwargs)
  File "/opt/MAD/mapadroid/madmin/routes/config.py", line 228, in settings_areas
    return self.process_element(**required_data)
  File "/opt/MAD/mapadroid/madmin/routes/config.py", line 158, in process_element
    included_data[section] = self._data_manager.get_root_resource(data_source)
  File "/opt/MAD/mapadroid/data_manager/__init__.py", line 80, in get_root_resource
    elem = resource_class(self, identifier=identifier)
  File "/opt/MAD/mapadroid/data_manager/modules/__init__.py", line 23, in AreaFactory
    return AREA_MAPPINGS[mode](data_manager, identifier=identifier)
  File "/opt/MAD/mapadroid/data_manager/modules/resource.py", line 186, in __init__
    self._load()
  File "/opt/MAD/mapadroid/data_manager/modules/area.py", line 41, in _load
    routecalc = self._data_manager.get_resource('routecalc', self._data['fields']['routecalc'])
  File "/opt/MAD/mapadroid/data_manager/__init__.py", line 38, in get_resource
    return modules.MAPPINGS[section](self, identifier=identifier)
  File "/opt/MAD/mapadroid/data_manager/modules/resource.py", line 186, in __init__
    self._load()
  File "/opt/MAD/mapadroid/data_manager/modules/routecalc.py", line 57, in _load
    raise UnknownIdentifier()
mapadroid.data_manager.dm_exceptions.UnknownIdentifier
[2020-06-15 14:57:09,753] ERROR in app: Exception on /settings/areas [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[06-15 14:57:09.75] [           madmin] [C] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "start.py", line 58, in run_thread
    run_thread_old(*args, **kwargs)
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/MAD/mapadroid/madmin/reverseproxy.py", line 26, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
> File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[06-15 14:57:09.75] [           madmin] [C] An unhanded exception occurred!
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7f1c3a54cbf8>
    └ <Thread(Thread-68, started daemon 139756415477504)>
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x7f1c1ca4a510>
    └ <Thread(Thread-68, started daemon 139756415477504)>

  File "start.py", line 58, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(Thread-68, started daemon 139756415477504)>,)
    └ <function Thread.run at 0x7f1c3a54c9d8>

  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-68, started daemon 139756415477504)>
    │    │        │    └ (<socket.socket fd=103, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 4000), raddr=...
    │    │        └ <Thread(Thread-68, started daemon 139756415477504)>
    │    └ <bound method ThreadingMixIn.process_request_thread of <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>>
    └ <Thread(Thread-68, started daemon 139756415477504)>
  File "/usr/lib/python3.6/socketserver.py", line 654, in process_request_thread
    self.finish_request(request, client_address)
    │    │              │        └ ('127.0.0.1', 44842)
    │    │              └ <socket.socket fd=103, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 4000), raddr=(...
    │    └ <function BaseServer.finish_request at 0x7f1c295f7840>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
    │    │                   │        │               └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>
    │    │                   │        └ ('127.0.0.1', 44842)
    │    │                   └ <socket.socket fd=103, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 4000), raddr=(...
    │    └ <class 'werkzeug.serving.WSGIRequestHandler'>
    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
    │    └ <function WSGIRequestHandler.handle at 0x7f1c29594e18>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 345, in handle
    BaseHTTPRequestHandler.handle(self)
    │                      │      └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>
    │                      └ <function BaseHTTPRequestHandler.handle at 0x7f1c2960ca60>
    └ <class 'http.server.BaseHTTPRequestHandler'>

  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
    │    └ <function WSGIRequestHandler.handle_one_request at 0x7f1c29516048>
    └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 379, in handle_one_request
    return self.run_wsgi()
           │    └ <function WSGIRequestHandler.run_wsgi at 0x7f1c29594d90>
           └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
    │       │    │      └ <Flask 'mapadroid.madmin.madmin'>
    │       │    └ <werkzeug.serving.ThreadedWSGIServer object at 0x7f1c1c01b0f0>
    │       └ <werkzeug.serving.WSGIRequestHandler object at 0x7f1c14521550>
    └ <function WSGIRequestHandler.run_wsgi.<locals>.execute at 0x7f1bec7671e0>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
                       │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f1bec767268>
                       │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=103>, 'wsgi.errors': <_io.TextIOWr...
                       └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
           │    │        │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f1bec767268>
           │    │        └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=103>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <mapadroid.madmin.reverseproxy.ReverseProxied object at 0x7f1c1c08ffd0>
           └ <Flask 'mapadroid.madmin.madmin'>

  File "/opt/MAD/mapadroid/madmin/reverseproxy.py", line 26, in __call__
    return self.app(environ, start_response)
           │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f1bec767268>
           │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=103>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <werkzeug.middleware.proxy_fix.ProxyFix object at 0x7f1c1ca2d5f8>
           └ <mapadroid.madmin.reverseproxy.ReverseProxied object at 0x7f1c1c08ffd0>

  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
           │    │   │        └ <function WSGIRequestHandler.run_wsgi.<locals>.start_response at 0x7f1bec767268>
           │    │   └ {'wsgi.version': (1, 0), 'wsgi.url_scheme': 'http', 'wsgi.input': <_io.BufferedReader name=103>, 'wsgi.errors': <_io.TextIOWr...
           │    └ <bound method Flask.wsgi_app of <Flask 'mapadroid.madmin.madmin'>>
           └ <werkzeug.middleware.proxy_fix.ProxyFix object at 0x7f1c1ca2d5f8>

> File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
               │    └ <function Flask.full_dispatch_request at 0x7f1c291b5b70>
               └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
           │    │                └ None
           │    └ <function Flask.finalize_request at 0x7f1c291b5bf8>
           └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
               │    │             └ None
               │    └ <function Flask.make_response at 0x7f1c291b5e18>
               └ <Flask 'mapadroid.madmin.madmin'>

  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"

TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.`
```

**Comment by Expl0dingBanana** [comment]
Please try the branch `multiinstance_routecalc_fix` to see if this resolves the issue.

`git fetch && git checkout multiinstance_routecalc_fix`

**Comment by spammer23** [comment]
I can visit area settings and walkers on this branche without erros, API not tested.

**Comment by dkmur** [comment]
quickly tested it, for both instances Im now able to:
- enter Area section without error and recalc route
- enter walker section and make adaptations
- use API to load new IV list

Only had a few minutes but i would say GREAT JOB !!!

**Comment by Expl0dingBanana** [comment]
@spammer23 any issues crop up?  if not ill merge the fix

**Comment by spammer23** [comment]
Looks fine for me :)
