### ISSUE TITLE
Apk Wizard cannot download Pogo apk on Raspberry Pi

### ISSUE THREAD

**Issue by Tabbomat** [Map-A-Droid/MAD#907]
Currently, the wizard cannot download the Pogo apk via  matlink-gpapi, it fails with the following error:

```
[06-16 12:10:32.56] [           system] [             wizard:260 ] [I] Searching for a new version of PoGo [arm64_v8a]
[06-16 12:10:32.96] [           system] [    gplay_connector:209 ] [I] Using cached token.
[06-16 12:10:38.88] [           system] [             wizard:270 ] [I] Newer version found on the Play Store: 0.177.1
[06-16 12:10:38.96] [           system] [    gplay_connector:209 ] [I] Using cached token.
[06-16 12:10:45.38] [           system] [    gplay_connector:62  ] [I] Starting download for com.nianticlabs.pokemongo
[06-16 12:10:46.48] [           system] [    gplay_connector:69  ] [E] Error while downloading com.nianticlabs.pokemongo : Unexpected end-group tag.
[06-16 12:10:46.49] [           system] [             wizard:145 ] [I] Issue downloading apk
[06-16 12:10:46.50] [           system] [             wizard:148 ] [W] Unable to successfully download the APK
[06-16 12:10:46.50] [           system] [    gplay_connector:209 ] [I] Using cached token.
[06-16 12:10:52.71] [           system] [    gplay_connector:62  ] [I] Starting download for com.nianticlabs.pokemongo
[06-16 12:10:53.74] [           system] [    gplay_connector:69  ] [E] Error while downloading com.nianticlabs.pokemongo : Unexpected end-group tag.
[06-16 12:10:53.75] [           system] [             wizard:145 ] [I] Issue downloading apk
[06-16 12:10:53.76] [           system] [             wizard:148 ] [W] Unable to successfully download the APK
[06-16 12:10:53.76] [           system] [    gplay_connector:209 ] [I] Using cached token.
[06-16 12:11:00.63] [           system] [    gplay_connector:62  ] [I] Starting download for com.nianticlabs.pokemongo
[06-16 12:11:01.98] [           system] [    gplay_connector:69  ] [E] Error while downloading com.nianticlabs.pokemongo : Unexpected end-group tag.
[06-16 12:11:01.99] [           system] [             wizard:145 ] [I] Issue downloading apk
```

This happens for both v7 and v8 pogo apk, but not for RGC or PD.

I'm using a Raspberry Pi 3B+, with Python 3.6.6 and matlink-gpapi==0.4.4.5. All requirements are up to date, MAD is currently on latest master.

According to Discord, on 18.05.2020 (https://discordapp.com/channels/465247740553592832/562515411149651983/712001536217055303) the wizard worked for me, but since 28.05.2020 (https://discordapp.com/channels/465247740553592832/562515411149651983/715490538736058398) it never worked.

I restarted MAD, did pip install -r requirements.txt, rebooted my Pi, but the issue still persists. At least one other person with a RPi reported similar issues in #help-english.

According to https://discordapp.com/channels/465247740553592832/562515411149651983/715555947552047147, it might be enough to simply ignore that specific error?

Edit: If it helps, this is the relevant section from a -v log when commenting out lines [68](https://github.com/Map-A-Droid/MAD/blob/6b923fc82ed73a12b45aef1a7ceb921fe254b6de/mapadroid/utils/gplay_connector.py#L68) to 70 in gplay_connector.py: 
```
[06-16 12:35:27.31] [           system] [              start:64  ] [C] An unhanded exception occurred!
Traceback (most recent call last):
  File "***/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x766d0660>
    └ <Thread(PackageWizard, started daemon 1574880368)>
  File "***/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    │    └ <function install_thread_excepthook.<locals>.run_thread at 0x6a15ea98>
    └ <Thread(PackageWizard, started daemon 1574880368)>

> File "start.py", line 58, in run_thread
    run_thread_old(*args, **kwargs)
    │               │       └ {}
    │               └ (<Thread(PackageWizard, started daemon 1574880368)>,)
    └ <function Thread.run at 0x766d0540>

  File "***/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
    │             │             └ <Thread(PackageWizard, started daemon 1574880368)>
    │             └ <Thread(PackageWizard, started daemon 1574880368)>
    └ <Thread(PackageWizard, started daemon 1574880368)>

  File "***/MAD/mapadroid/mad_apk/wizard.py", line 82, in apk_download
    self.download_pogo(architecture)
    │    │             └ <APK_Arch.arm64_v8a: 2>
    │    └ <function APKWizard.download_pogo at 0x6e383228>
    └ <mapadroid.mad_apk.wizard.APKWizard object at 0x68baa1d0>

  File "***/MAD/mapadroid/mad_apk/wizard.py", line 139, in download_pogo
    downloaded_file = self.gpconn.download(APK_Package.pogo.value)
                      │    │      │        │           │    └ <types.DynamicClassAttribute object at 0x766ab4b0>
                      │    │      │        │           └ <APK_Package.pogo: 'com.nianticlabs.pokemongo'>
                      │    │      │        └ <enum 'APK_Package'>
                      │    │      └ <function GPlayConnector.download at 0x6e381c00>
                      │    └ <mapadroid.utils.gplay_connector.GPlayConnector object at 0x6953f2f0>
                      └ <mapadroid.mad_apk.wizard.APKWizard object at 0x68baa1d0>

  File "***/MAD/mapadroid/utils/gplay_connector.py", line 64, in download
    data_iter = method(packagename, expansion_files=True)
                │      └ 'com.nianticlabs.pokemongo'
                └ <bound method GooglePlayAPI.download of <gpapi.googleplay.GooglePlayAPI object at 0x695622f0>>

  File "***/python3.6/site-packages/gpapi/googleplay.py", line 618, in download
    self.log(packageName)
    │    │   └ 'com.nianticlabs.pokemongo'
    │    └ <function GooglePlayAPI.log at 0x6e381660>
    └ <gpapi.googleplay.GooglePlayAPI object at 0x695622f0>
  File "***/python3.6/site-packages/gpapi/googleplay.py", line 645, in log
    response = googleplay_pb2.ResponseWrapper.FromString(response.content)
               │              │               │          │        └ <property object at 0x6e838c60>
               │              │               │          └ <Response [404]>
               │              │               └ <staticmethod object at 0x6e42e0b0>
               │              └ <class 'googleplay_pb2.ResponseWrapper'>
               └ <module 'gpapi.googleplay_pb2' from '***/python3.6/site-packages/gpapi/googleplay_pb2.py'>
  File "***/python3.6/site-packages/google/protobuf/internal/python_message.py", line 794, in FromString
    message.MergeFromString(s)
    │       │               └ b'<!DOCTYPE html><html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=devic...
    │       └ <function _AddMergeFromStringMethod.<locals>.MergeFromString at 0x6e42d540>
    └
  File "***/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1130, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
          │           └ <class 'google.protobuf.message.DecodeError'>
          └ <module 'google.protobuf.message' from '***/python3.6/site-packages/google/protobuf/messag...

google.protobuf.message.DecodeError: Unexpected end-group tag.
```

**Comment by LegitDongo** [comment]
Tried this out, having the same issue to the T

**Comment by Expl0dingBanana** [comment]
This issue only appears to affect RPis as that message is a warning vs exception on other systems.

**Comment by Expl0dingBanana** [comment]
Please try the branch `rpi_wizard_fix` as it should resolve the download problem

**Comment by Tabbomat** [comment]
That does indeed resolve the issue. Thanks
